### ISSUE TITLE
Website's CSV not working?

### ISSUE THREAD

**Issue by kpjVideo** [fiorix/freegeoip#103]
Hello, I was just trying to use the csv function on: http://freegeoip.net/csv however it seems to not work/be offline. Any ideas on when this will be back up? Currently the normal site is fine.

**Comment by fiorix** [comment]
You're missing a tailing slash in the URL, it's /csv/ fwiw. Also, I'm having infinite trouble to run the public service and having almost no time to work on it. If you need better SLA it's ideal that you download the software and run on your server.
