### ISSUE TITLE
Error: "listen tcp [MY_IP]:8080: bind: cannot assign requested address"

### ISSUE THREAD

**Issue by jwerre** [fiorix/freegeoip#108]
Trying to run freegeoip for the first time and I am getting this error.

    >  $GOPATH/bin/freegeoip -addr="mydomain.com:8080"
       freegeoip server starting on geo.surveyplanet.com:8080
       listen tcp <MY_IP>:8080: bind: cannot assign requested address

Any idea why this would be happening?

**Comment by fiorix** [comment]
You shouldn't use "mydomain" in there, put either the IP address of the NIC you want to bind to, or 0.0.0.0 to bind to all available interfaces. If you still get the error, it means you already have something listening on port 8080. In that case, change the port to something else.

**Comment by jwerre** [comment]
That's just a pseudo domain. I've tried all different types of ports and don't have anything running any ports frankly:

    netstat -a -t
    Active Internet connections (servers and established)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State      
    tcp        0      0 *:http                  *:*                     LISTEN     
    tcp        0      0 *:ssh                   *:*                     LISTEN     
    tcp        0    412 ip-172-31-31-30.us-:ssh 50-47-1-34.evrt.w:51581 ESTABLISHED
    tcp6       0      0 [::]:http               [::]:*                  LISTEN     
    tcp6       0      0 [::]:ssh                [::]:*                  LISTEN

**Comment by fiorix** [comment]
Try just :8080

**Comment by jwerre** [comment]
Ahhhh... that did it. Why did that work?

**Comment by fiorix** [comment]
That's the same as setting 0.0.0.0:8080, bind to all interfaces.
