### ISSUE TITLE
Update question

### ISSUE THREAD

**Issue by wamatt** [fiorix/freegeoip#109]
I tried poking around, but couldn't see if it supports changing the URL to update from the commercial GeoIP2 db?

**Comment by fiorix** [comment]
Sure does. You can either host it somewhere and use -db http://your-server <http://your-server/> or -db /path/to/file. Both cases support automatic updates. In the URL case, it’ll poke the server every day (configurable) to see if there’s a new version available. In the case of local file, it reloads it automatically if the file is overwritten.

**Comment by wamatt** [comment]
That's good to know,ty. btw on a side note... super impressed/surprised by how well this open source project is managed. great job :+1:

**Comment by fiorix** [comment]
Thanks ;)
