### ISSUE TITLE
Country data accuracy

### ISSUE THREAD

**Issue by wamatt** [fiorix/freegeoip#110]
While I've read reports that the city data is much better in the commercial version, does anyone have idea on how accurate the GeoLite2 country data is compared with the GeoIP2 commercial db?

**Comment by christophlingg** [comment]
I could not find specific statements about accuracy on MaxMind webpage neither. However you can easily check some ip address on their [demo page](https://www.maxmind.com/en/geoip-demo) and compare results with those from the lite version.

We observed deviations from both services of 50 km.

**Comment by fiorix** [comment]
I'm not sure either but you can probably get a hold of their sales people to expand on this. If you do, please report back so others can understand the difference. Will leave this issue open for now.

**Comment by oschwald** [comment]
You can check out the [GeoIP2 Accuracy page](https://www.maxmind.com/en/geoip2-city-database-accuracy), which includes GeoLite2.

**Comment by fiorix** [comment]
This is done.
