### ISSUE TITLE
Add gzip option and Cache headers

### ISSUE THREAD

**Issue by fustic** [fiorix/freegeoip#113]
First of all, thank you for the service.
I would like to suggest to have such an options to enable gzipping and Cache headers. Especially for json response on request to https://freegeoip.net/json/, for example.

**Comment by williamsjj** [comment]
We run freegeoip behind Nginx which can easily provide this.

**Comment by fustic** [comment]
@williamsjj I will do the same, thank you

**Comment by fiorix** [comment]
That's right, usually a reverse proxy like nginx or haproxy can easily provide that. However, I'm not sure about gzip since the response is so small in bytes that it may not be worth compressing it.
