### ISSUE TITLE
build instructions missing

### ISSUE THREAD

**Issue by zabbal** [fiorix/freegeoip#114]
The readme refers to running ./freegeoip to get ip db during the first run but it's completely unclear where this executable supposed to come from. Is it smth from cmd folder? Is it result of building something somehow in toplevel folder? Is it some script?

**Comment by fiorix** [comment]
One line above the Usage has a link to download pre-compiled binaries from https://github.com/fiorix/freegeoip/releases :)

If you want to build it yourself, then run `go build` in the `cmd/freegeoip` directory.

**Comment by zabbal** [comment]
The build fails with following error:

main.go:21:2: cannot find package "github.com/fiorix/freegeoip" in any of:
        /usr/lib/go/src/pkg/github.com/fiorix/freegeoip (from $GOROOT)
        ($GOPATH not set)
main.go:22:2: cannot find package "github.com/fiorix/go-redis/redis" in any of:
        /usr/lib/go/src/pkg/github.com/fiorix/go-redis/redis (from $GOROOT)
        ($GOPATH not set)
main.go:23:2: cannot find package "github.com/gorilla/context" in any of:
        /usr/lib/go/src/pkg/github.com/gorilla/context (from $GOROOT)
        ($GOPATH not set)

What's the right way to provide required dependencies?

**Comment by fiorix** [comment]
First you need a proper Go development environment with GOROOT and GOPATH environment variables set, then you'd do a "go get" to download the dependencies and build it.
