### ISSUE TITLE
freegeoip and DNS cash conflict

### ISSUE THREAD

**Issue by Neville-Hillyer** [fiorix/freegeoip#117]
I use, for example,
https://freegeoip.net/json/google.com?callback=z
but the combination of freegeoip.net and OS X DNS cache results in a slow and unreliable service.

Any thoughts?

I have now changed this version:
&#60;script type="text/javascript">function z (x){ document.getElementById('y').innerHTML=x.ip }&#60;/script>
&#60;script type="text/javascript" src="https://freegeoip.net/json/zero.eu.org?callback=z"> &#60;/script>

To this faster and more reliable version:
&#60;script type="text/javascript">function z (x){ document.getElementById('y').innerHTML=x.query }</script>
&#60;script type='text/javascript' src='http://ip-api.com/json/zero.eu.org?callback=z'> &#60;/script>

This can be seen working at: http://meon.zero.eu.org/

I am happy to do limited testing to help resolve the freegeoip.net issue.

**Comment by fiorix** [comment]
I don't see the correlation between OS X and DNS resolution here... when you query freegeoip using a hostname, it is resolved by the freegeoip server, not OS X.

It's possible that you've been hitting a dead server, since some of my servers in the pool have been freezing due to high usage for the past 2 weeks.

**Comment by Neville-Hillyer** [comment]
A dead server would explain it.

It works OK for me for a while after flushing my DNS but eventually freezes attempting to contact freegeoip.net - sometimes indefinitely and sometimes for over a minute. This happens with both browser and curl. It sometimes resolves itself after about 10 minutes if I don't flush my DNS cache first.

I wonder why you don't have more reports about this. Could it affect OS X more than other platforms?

**Comment by fiorix** [comment]
It's possible that when you flush the DNS it resolves to a different IP from the pool:

   $ host freegeoip.net
   freegeoip.net has address 104.236.251.84
   freegeoip.net has address 104.236.250.71
   freegeoip.net has address 104.131.173.122
   freegeoip.net has IPv6 address 2604:a880:800:10::7de:2001
   freegeoip.net has IPv6 address 2604:a880:800:10::336:2001
   freegeoip.net has IPv6 address 2604:a880:800:10::336:d001

**Comment by Neville-Hillyer** [comment]
This is probably a function of your pool setup. Can you monitor your servers and automatically restart or remove them when they fail?

Earlier today I tried testing with one of your IPs but it did not work. Could it have been a frozen IP or have you not permitted IP access?

**Comment by fiorix** [comment]
The monitoring system I used is kinda broken and I have no time to work on that for now. If you need better SLA please download the freegeoip web server and deploy on your network. I do what is possible to keep freegeoip.net up and running but the internet is a wild place and things break.

**Comment by Neville-Hillyer** [comment]
I am unable to deploy freegeoip on my G3 / OS 9 server so will use http://ip-api.com for the time being.

Thanks for your speedy candid replies.
