### ISSUE TITLE
FreegeoIP inaccurate while MaxMind is accurate

### ISSUE THREAD

**Issue by that1guy** [fiorix/freegeoip#118]
I was under the impression that FreeGeoIP syncs with MaxMind.  Is this correct.  This IP has been incorrect on FreeGeoIP for months.  Not calling out software, I love FGIP but just thought to raise this.

###### 76.21.93.40 geolocates San Francisco on MaxMind (Correct)
````
GeoIP2 Precision: City Results
IP Address	Country Code	Location	Postal Code	Coordinates	ISP	Organization	Domain	Metro Code
216.38.134.18	US	San Francisco,
California,
United States,
North America	94111	37.7989,
-122.3984	Fastmetrics	The VAULT		807
````

###### 76.21.93.40 geolocates Santa Clara on FreeGeoIP (not correct)
````
{"ip":"76.21.93.50","country_code":"US","country_name":"United States","region_code":"CA","region_name":"California","city":"Santa Clara","zip_code":"95052","time_zone":"America/Los_Angeles","latitude":37.354,"longitude":-121.956,"metro_code":807}
````

**Comment by williamsjj** [comment]
I'd imagine it's the difference between the Lite version that FreeGeoIP uses and the commercial DB that the MaxMind "check your IP" form uses.

**Comment by that1guy** [comment]
Ahhh.. this makes sense.. now wondering if it's possible to load MaxMinds complete GeoIP2 db to FGIP API..

**Comment by williamsjj** [comment]
I believe both DBs are compatible with the MaxMind API that loads them. You just have to pay MaxMind for it.

**Comment by that1guy** [comment]
Yep.  Thanks!  I'll look into this.. Cheers!

**Comment by fiorix** [comment]
fwiw for every query freegeoip will return the date of the database in the `X-Database-Date` header:

    $ curl -i freegeoip.net/json/
    HTTP/1.1 200 OK
    Server: nginx/1.4.6 (Ubuntu)
    Date: Tue, 28 Apr 2015 23:27:52 GMT
    Content-Type: application/json
    Content-Length: 226
    Connection: keep-alive
    Access-Control-Allow-Method: GET, HEAD, OPTIONS
    Access-Control-Allow-Origin: *
    X-Database-Date: Wed, 08 Apr 2015 16:56:28 GMT
    
    ... results

I usually never touch the server and they update the database automatically so this helps to keep track of what version it's running.

**Comment by kribblo** [comment]
Did any one verify if the paid for databases could be used by freegeoip, if hosting the server self? If so, anyone also know how? (Note, have not yet paid for the service, just assume it's also a download but maybe password protected?)

Thanks!

**Comment by fiorix** [comment]
It should work just fine. If you point freegeoip to a file it'll reload the file when it's overwritten, so you can update it easily with no downtime; or you can host the db file elsewhere and point freegeoip to a url, in which case it'll poll for updates based on your settings.
