### ISSUE TITLE
ISP information 

### ISSUE THREAD

**Issue by rdonmez** [fiorix/freegeoip#121]
i hope, freegeoip provides to ISP information as soon as possible :)

**Comment by kz26** [comment]
Unfortunately it appears this is not possible without major modifications to the codebase because freegeoip uses the GeoLite2 database format, but MaxMind currently provides ISP/ASN info only in the legacy GeoLite1 format.

**Comment by fiorix** [comment]
Earlier versions of freegeoip imported data from multiple sources, including GeoLite legacy, from csv into a sqlite. It was removed when I switched over to the binary GeoLite 2 db. We could, for example, load/index ISP data into an internal db to serve it.

**Comment by kz26** [comment]
I had actually been using telize.com because it includes IP and ASN data, but now that that service appears to be shutting down I'm thinking of rolling my own version using the GeoLite 1 databases. Out of curiosity, is there any noticeable difference in performance between doing an SQL lookup vs. the current in-memory binary lookup?

**Comment by oschwald** [comment]
Another option would be to transform the GeoLite Legacy database into the binary format used by GeoLite2. There is a [tutorial on how to write out this format](http://blog.maxmind.com/2015/09/29/building-your-own-mmdb-database-for-fun-and-profit/), and it would mimize the special code needed in the daemon.

**Comment by fiorix** [comment]
Not happening.

**Comment by phlegx** [comment]
Is it possible now with freegeoip? MaxMind has GeoLite2 ASN database: http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by fiorix** [comment]
I have no plans to implement this atm.
