### ISSUE TITLE
Cell network -  Quota exceeded

### ISSUE THREAD

**Issue by gr225607** [fiorix/freegeoip#124]
Hi,
Whenever I try the service from my mobile on a cell network the quota is always exceeded... and way around this? From my Wifi - no problem.

**Comment by gr225607** [comment]
It seems to be my phone, I had privacy guard on, but when I take it off I'm getting error HTTP 0, and sometimes IP of 127.0.0.1, yet I can still access the web...

**Comment by fiorix** [comment]
Sounds like a bad network, unrelated to the freegeoip service.
