### ISSUE TITLE
Is there a reason to trim Lat/Long?

### ISSUE THREAD

**Issue by if-kenn** [fiorix/freegeoip#125]
It appears that freegeoip trims the latitude and longitude to 3 decimal places instead of the 4 that is in the data files. Is there a reason for this?

**Comment by fiorix** [comment]
No particular reason. Send a pull request if you'd like it fixed at 4 decimals.

**Comment by if-kenn** [comment]
send PR

**Comment by fiorix** [comment]
Done. Thanks!

**Comment by fiorix** [comment]
I'll schedule an update for the weekend, if possible. Otherwise some time next week.
