### ISSUE TITLE
no city / geocoordinates without fractions

### ISSUE THREAD

**Issue by neandr** [fiorix/freegeoip#126]
Since some time I recognize the service not returns the city name and only "Latitude: 51 Longitude: 9".

When I started to use your service all was fine, then I felt at the weekends the values are as described above, but now it's truncated all the time.

Any advice?

**Comment by fiorix** [comment]
This means the IP you're querying is not in the database. You can submit corrections to MaxMind directly and it'll make it to freegeoip in the next update. They update the database every second Tuesday per month iirc and the freegeoip service updates automatically.
