### ISSUE TITLE
Ability to query multiple IP's and return an array/map of resolved addresses

### ISSUE THREAD

**Issue by prak5190** [fiorix/freegeoip#128]
It would be nice if we could query freegeoip with a comma separated list of IPs like 
`https://freegeoip.net/json/github.com,google.com,172.1.5.2` and get a map of resolved entries like 

	{
		"google.com": {
			"ip": "192.30.252.130",
			"country_code": "US",
			"country_name": "United States",
			"region_code": "CA",
			"region_name": "California",
			"city": "San Francisco",
			"zip_code": "94107",
			"time_zone": "America/Los_Angeles",
			"latitude": 37.77,
			"longitude": -122.394,
			"metro_code": 807
		},
		"github.com": {
			"ip": "192.30.252.130",
			"country_code": "US",
			"country_name": "United States",
			"region_code": "CA",
			"region_name": "California",
			"city": "San Francisco",
			"zip_code": "94107",
			"time_zone": "America/Los_Angeles",
			"latitude": 37.77,
			"longitude": -122.394,
			"metro_code": 807
		},
		"172.1.5.2": {
			"error": true
		}
	}

It will be a simple array for CSV and XML. I can contribute a pull if the author is ok with it ?

**Comment by fiorix** [comment]
You can achieve almost the same by having a persistent client making multiple requests. The problem of allowing bulk calls like this is that you have to handle partial failures, and it'd cause troubles with quota as well.
