### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Adenes88** [fiorix/freegeoip#129]
Hi. The API, and the website as well, is unable to achieve information frmm any IP address lately (past seven days). Is there something wrong? I'm using this API in a software that I'm developing, but since it is not working I'm facing several problems. Any help?
Thanks in advance.

**Comment by fiorix** [comment]
That's accurate. I'm troubleshooting an issue with one of the servers atm and will update soon.

This is unfortunate but happens once in a while... the box is up but the network is failing to arp to its gw, arp table says incomplete.
DigitalOcean support is engaged.

**Comment by Adenes88** [comment]
Ok, thanks for the feedback. I'm using the API as part of my Final Project at University. Do you have any idea when the API will be working again? My presentation  is within 10 days so right now is a bit complicated to install the database on my server, since I already submitted my work as it is. 
Anyway, if it is not working by then I have a few days after the presentation for possible corrections, then I'll probably do it.
Once again, thank you.

**Comment by fiorix** [comment]
It's just one of the servers that is failing on both ipv4 and ipv6. The other two are up and running, but it turns out that the one your client is resolving to (when querying freegeoip.net) is the one that is down.

You could query the other two:

    freegeoip.net has address 104.131.173.122 (temporarily down)
    freegeoip.net has address 104.236.250.71
    freegeoip.net has address 104.236.251.84

**Comment by Adenes88** [comment]
That's great! I'll try that.
Thank you.

**Comment by fiorix** [comment]
Server is back, should work fine by querying freegeoip.net now.
