### ISSUE TITLE
Error fetching databases when behind ipv6.

### ISSUE THREAD

**Issue by minxomat** [fiorix/freegeoip#130]
Installing freegeoip on a server that is connected exclusively via ipv6 (most datacenters) fails with an tcp lookup error when trying to download the latest databases.

```
2015/06/26 20:40:13 database error: Database update failed: Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz: dial tcp: lookup geolite.maxmind.com: no DNS servers
```

**Comment by minxomat** [comment]
This is apparently a [known issue](https://github.com/docker/docker/issues/1470) on servers in OVH datacenters and there is a workaround.

**Comment by minxomat** [comment]
This is how to solve it:

```
sudo aptitude remove bind9 resolvconf
gksudo gedit /etc/resolv.conf
```
then add this the the file, save, restart freegeoip:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by fiorix** [comment]
:)
