### ISSUE TITLE
Problem using the docker image with haproxy 

### ISSUE THREAD

**Issue by danecando** [fiorix/freegeoip#132]
I have it setup on a server using the tutum.co docker service. It works fine if I access the container directly as far as providing the accurate geo ip information but when I put haproxy in front of it with ssl it seems to be returning an internal ip address. The value of GEOIP_API_PORT_8080_TCP_ADDR is 10.7.0.1 and the only ip it's returning is 10.7.0.2 . This is all a bit new to me so any advice to getting this working would be much appreciated.

**Comment by fiorix** [comment]
You have to configure haproxy to pass the client IP in the `X-Forwarded-For` header and run freegeoip with `-use-x-forwarded-for`.

**Comment by danecando** [comment]
thanks
