### ISSUE TITLE
Start FreeGeoIP on Startup?

### ISSUE THREAD

**Issue by Especially** [fiorix/freegeoip#135]
I wanted to know how I can have freegeoip running in the background once i start up my VPS without having to explicitly run the program? I'm new to using VPS programs and so I apologize if this question seems ridiculous. I'm running Linux CentOS 7, and so how would I make sure that on boot, freegeoip is running in the background?

**Comment by fiorix** [comment]
You'd need a systemd unit file to start it for you on boot.

**Comment by Especially** [comment]
I tried writing a systemd unit file as `/usr/lib/systemd/system/freegeoip.service` with the following:

**Excerpt from /usr/lib/systemd/system/freegeoip.service:**

    [Unit]
    Description=Free GeoIP in Background
    After=network.target
    
    [Service]
    Type=simple
    ExecStart=/home/jevel/freegeoip/freegeoip -s
    Restart=on-abort

    [Install]
    WantedBy=multi-user.target

However, when I call `sudo systemctl status freegeoip`, i receive the following error:

    freegeoip.service - Free GeoIP in Background
    Loaded: loaded (/usr/lib/systemd/system/freegeoip.service; disabled)
    Active: failed (Result: exit-code) since Mon 2015-08-10 19:43:38 EDT; 7s ago
    Process: 21391 ExecStart=/home/jevel/freegeoip/freegeoip -s (code=exited, status=2)
    Main PID: 21391 (code=exited, status=2)

    Aug 10 19:43:38 jupiter freegeoip[21391]: -silent
    Aug 10 19:43:38 jupiter freegeoip[21391]: Do not log requests to stderr
    Aug 10 19:43:38 jupiter freegeoip[21391]: -update duration
    Aug 10 19:43:38 jupiter freegeoip[21391]: Database update check interval (default 24h0m0s)
    Aug 10 19:43:38 jupiter freegeoip[21391]: -use-x-forwarded-for
    Aug 10 19:43:38 jupiter freegeoip[21391]: Use the X-Forwarded-For header when available
    Aug 10 19:43:38 jupiter freegeoip[21391]: -version
    Aug 10 19:43:38 jupiter freegeoip[21391]: Show version and exit
    Aug 10 19:43:38 jupiter systemd[1]: freegeoip.service: main process exited, code=exited, status=2/...MENT
    Aug 10 19:43:38 jupiter systemd[1]: Unit freegeoip.service entered failed state.

**Comment by fiorix** [comment]
The `ExecStart` command `freegeoip -s` does not exist. Perhaps you want `freegeoip -silent` ?

**Comment by Especially** [comment]
Oh jeez, whoops, that definitely solved it! Thank you
