### ISSUE TITLE
JSONP not supported by /json endpoint

### ISSUE THREAD

**Issue by doshprompt** [fiorix/freegeoip#138]

**Comment by fiorix** [comment]
JSON is supported, you have to add `?callback=x` to the URL.

Example:

    $ curl -s https://freegeoip.net/json/github.com?callback=?
    ?({"ip":"192.30.252.130","country_code":"US","country_name":"United States","region_code":"CA","region_name":"California","city":"San Francisco","zip_code":"94107","time_zone":"America/Los_Angeles","latitude":37.77,"longitude":-122.394 "metro_code":807});

**Comment by doshprompt** [comment]
@fiorix I get a parse error when I try to do it in the browser, both in safari and in chrome.

**Comment by fiorix** [comment]
Just tried with the following and it works for me on Safari:

	<html>
	<head>
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script>
	$.ajax({
		url: 'https://freegeoip.net/json/?callback=f',
		jsonpCallback: 'f',
		dataType: 'jsonp',
		type: 'GET',
		success: function(resp) {
			$('#result').html(JSON.stringify(resp));
		}
	});
	</script>
	</head>
	<body>
		<div id="result">Loading...</div>
	</body>
	</html>

**Comment by doshprompt** [comment]
@fiorix my previous comment got deleted, yes I did mention that I get a parse error, probably a framework quirk as I am using angularjs, I will take a look on my end, but thank you so much for responding so promptly! I am very grateful for the service you provide and like it a lot!

**Comment by fiorix** [comment]
Cool, no problem. I've used it on angular and it works too... Good luck! :)
