### ISSUE TITLE
Extension for zip code lookup?

### ISSUE THREAD

**Issue by dustinb** [fiorix/freegeoip#139]
Would this database allow adding feature or extension to lookup information by zip code?  Could use new endpoint /zip/json/90210 or auto identify the query as a zip code with the existing endpoint /json/90210

I have need for both types of lookups. Although it's not really geocoding if the data is already there would be nicer than another service.

**Comment by fiorix** [comment]
Seems like the current db does not support lookups by zip code.
Docs: http://godoc.org/github.com/oschwald/geoip2-golang

 Lookup functions in the `Reader` type only take IP addresses.
