### ISSUE TITLE
Update the docs for installation

### ISSUE THREAD

**Issue by anshbansal** [fiorix/freegeoip#141]
I was upgrading this from an older version when I saw that installation instructions in older versions are better than the present README.md. Should probably update them.

Make sure Go is installed and both $GOROOT and $GOPATH are set, then run:

        apt-get install build-essential libsqlite3-dev pkg-config
        go get github.com/fiorix/freegeoip
        cd $GOPATH/src/github.com/fiorix/freegeoip
        go build

**Comment by fiorix** [comment]
Maybe you have an old version, we don't use sqlite anymore since v3.

**Comment by anshbansal** [comment]
Yes the instructions are copied from an older version. I was trying to convey that the part about building is not present in the current installation instructions.
