### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by shiv86** [fiorix/freegeoip#142]
Completely new to this. Could you recommend step on how to host this on an amazon ec2 instance with say apache tomcat ?

**Comment by fiorix** [comment]
The freegeoip web server is a binary program that can handle http itself. There's no need for apache or tomcat, unless you want to use them to reverse proxy to freegeoip.

For running, you have quite a few options:

1. The easiest would be using Docker:

    docker run -d -p 8080:8080 fiorix/freegeoip

2. You could download the released tarball for your platform from https://github.com/fiorix/freegeoip/releases and deploy to your system using upstart or a systemd unit file to run it.

3. Under `cmd/freegeoip` there's a `deploy` directory with an ansible playbook that can be used to deploy freegeoip on any cloud or bare metal environment with a single command. Check out the README in that directory for details. That's my preferred way of running it, and you could tweak it to deploy using #1 on your cloud servers.

4. For the brave, download the source code and build. freegeoip is a Go package that you could embed in your own http server pretty easily.

For all the above, running it is usually a breeze. By default it will download the database from MaxMind in background and keep it up to date automatically, so no extra work for us. It's pretty much fire and forget.
