### ISSUE TITLE
Frontend no longer works (returns 404's)

### ISSUE THREAD

**Issue by jshimko** [fiorix/freegeoip#143]
I pulled the latest Docker image recently and the frontend no longer appears to be available.  I can also see the app returning 404's in the container logs any time something hits the root of the domain `/`.  API calls still work fine though.

We weren't really using the frontend, but I assume this change wasn't intentional and thought I should point it out.

**Comment by fiorix** [comment]
There are instructions in the updated Dockerfile, at the very bottom.
Have you tried that?

**Comment by jshimko** [comment]
Ha!  Of course there is.  :)

Sorry, disregard.
