### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by khfurletti** [fiorix/freegeoip#147]
Getting errors on the geolocation service this morning.  http://www.outageanalyzer.com/?id=15622547

**Comment by leoandrews** [comment]
+1

**Comment by fiorix** [comment]
It's back. Please download the server and run it yourself for better SLA.

**Comment by leoandrews** [comment]
Rude

**Comment by fiorix** [comment]
Hi @leoandrews, nothing personal here. I'm not giving enough attention to the public service + frequent DDoS + hosting breaking + pricing etc. Sorry to sound rude but in fact running it yourself is by far the best option. Me and other contributors have made the software super easy to deploy anywhere and require minimum to no maintenance.
