### ISSUE TITLE
Can't open any other page

### ISSUE THREAD

**Issue by stojankukrika** [fiorix/freegeoip#148]
Hi,
I add your great plugin to show in text input where user comes from. But I have other problem. when plugin is added I can't click on any link or button on page. Web browser shows me a link in url but didn't open that url. When I click to open in new tab, he open it url correctly. 
Can anybody help me? Please.

**Comment by fiorix** [comment]
Hi, not sure I understand what the problem is. What plugin are you talking about?

**Comment by stojankukrika** [comment]
I use this page:
https://github.com/fiorix/freegeoip/blob/master/cmd/freegeoip/public/index.html
to show geo location for my visitors on my website:
http://freelenser.rs.sr/

But then I see that I can't click on any link on page. Did you maybe know where is problem?

**Comment by fiorix** [comment]
Not quite sure but when I open your site there's a couple HTTP 404 on the browser's console. Missing bootstrap and angularjs.

**Comment by stojankukrika** [comment]
I find a problem. TNX.Sorry for hindering ;)
