### ISSUE TITLE
Empty result on request without an IP

### ISSUE THREAD

**Issue by ka8725** [fiorix/freegeoip#149]
I'm expecting the following behavior:

```
curl http://freegeoip.net/json/  
curl h{"ip":"93.85.20.132","country_code":"BY","country_name":"Belarus","region_code":"HR","region_name":"Grodnenskaya","city":"Hrodna","zip_code":"","time_zone":"Europe/Minsk","latitude":53.688,"longitude":23.826,"metro_code":0}
```

I have run `freegeoip` from the latest release. DB is downloaded:

```
./freegeoip
2015/11/10 08:15:37 freegeoip server starting on :8080
2015/11/10 08:15:37 database loaded: /var/folders/77/7c55d4zx45j3rd2pbjhl6pk80000gn/T/freegeoip/db.gz
```

And I have the following result:

```
curl http://freegeoip.net/json/
{"ip":"93.85.20.132","country_code":"BY","country_name":"Belarus","region_code":"HR","region_name":"Grodnenskaya","city":"Hrodna","zip_code":"","time_zone":"Europe/Minsk","latitude":53.688,"longitude":23.826,"metro_code":0}
```

It's empty. Am I missed something?

**Comment by fiorix** [comment]
When you query localhost, your source IP is localhost, results in empty response.

**Comment by ka8725** [comment]
Actually installing `docker` on a server didn't helper either. In case of desiring the feature and installing freegoip server via `docker` a custom image should be build with the `-use-x-forwarded-for` option (https://github.com/fiorix/freegeoip/blob/master/Dockerfile#L18). May be document this README?

**Comment by fiorix** [comment]
You can just pass that option to your container as an argument. What's wrong with that?

    $ docker run --rm -it fiorix/freegeoip -help
    Usage of /go/bin/freegeoip:
    ...

**Comment by ka8725** [comment]
It works. Thanks!
