### ISSUE TITLE
Request for additional command line arguments

### ISSUE THREAD

**Issue by spprakash** [fiorix/freegeoip#151]
Hi fiorix,

I am trying to install freegeoip on my own server and by default it's starting on port 8080. Also downloading the db file to tmp directory. 

Can we please add additional command line arguments for better usability?
1) To specify the port on which the service to Run
2) To specify the location to where the DB file has to be downloaded/saved. 
     I can see an option to specify the location of DB file. But will the DB file gets auto-updated with this option?
3) To specify the location of log file.

Thanks in advance.

**Comment by fiorix** [comment]
Hi, have you tried `-help`?

You can set the [ip]:port with the `-http` option: `freegeoip -http=:8888` for example. The database is downloaded to the directory pointed to by the TMPDIR environment variable, so you can change like `TMPDIR=/path/to/tmpdir freegeoip` and logs are always written to stderr so you can either redirect them or let systems like systemd, upstart, or docker, capture the output as it normally would.
