### ISSUE TITLE
windows GO issue

### ISSUE THREAD

**Issue by zechnkaas** [fiorix/freegeoip#152]
did something change in the go Package?

the last version i made was 3.0.5 and it worked fine.

when i try to make the 3.0.8 Package and start the exe it runs the service and downloads the DB but everytime i try to query i get an 404 error page. (tried to make 32 and 64 bit)

any ideas ?
ty

**Comment by fiorix** [comment]
Yes, something did change and I made a mistake to use `filepath` instead of `path` to set the URI e.g. /json/ and so on. Using `filepath` caused it to have backslash not slash in the path. This merge should fix it, please give it a try and let me know. 3.0.9 is for you.

**Comment by zechnkaas** [comment]
TY very much!
3.0.9 works again like a charm :+1: 

ty for your work and that nice little and simple program :)
