### ISSUE TITLE
Network not responding, intermittently

### ISSUE THREAD

**Issue by victorngkp** [fiorix/freegeoip#153]
When trying to geocode an IP via Ajax, intermittently I get no response. Here's the screenshot on the Console and Network respectively:

![screen shot 2015-12-16 at 12 02 10 pm](https://cloud.githubusercontent.com/assets/397034/11831823/4086c866-a3ed-11e5-9b27-57a2e78bbb44.png)

![screen shot 2015-12-16 at 12 01 52 pm](https://cloud.githubusercontent.com/assets/397034/11831826/43ac5326-a3ed-11e5-8bac-76ae0af6f85e.png)

I wonder if this is due to server issue, or any limitation on the free usage? I won't hit the limit of free usage because I geocode less than 100 times a day.

Here's when it works on Console and Network:

![screen shot 2015-12-16 at 12 14 49 pm](https://cloud.githubusercontent.com/assets/397034/11831967/bc86a016-a3ee-11e5-8919-90016d1930c0.png)

![screen shot 2015-12-16 at 12 15 00 pm](https://cloud.githubusercontent.com/assets/397034/11831969/bfddc046-a3ee-11e5-8d56-241ff5f56da5.png)

The screenshots above were done on Firefox, here's what Chrome gave me:

![screen shot 2015-12-16 at 2 22 02 pm](https://cloud.githubusercontent.com/assets/397034/11833717/82e4e04a-a400-11e5-9d6c-932678d0159c.png)

It stalled for a while before it hits again.

I tried hitting refresh for consecutive 5 times, and usually on the 5th time I hit this issue. But not if I copy-pate the link `http://freegeoip.net/json/175.139.187.185` directly to the address bar and keep refreshing, which doesn't appear to have any problem.

**Comment by fiorix** [comment]
Not sure what's going on. No anomalies in the monitoring system and I can access the site normally. I'm on vacation without access to my computer atm so will look again later.

**Comment by victorngkp** [comment]
Could it be CLoudFront acting up?

**Comment by makati82** [comment]
Is this issue fixed ? I am seeing that intermittently network is not responding. Please see the attached image. 

![image](https://cloud.githubusercontent.com/assets/17544261/13391622/79059976-defb-11e5-89f8-042145330c5d.png)

**Comment by johansolve** [comment]
Lots of 503 now.

**Comment by fiorix** [comment]
Yeah my servers can't keep up with the traffic, there's just too much. It starts returning 503 when the quota system (redis) takes longer than 1s to respond.

http://i.imgur.com/hkeyA5T.png

A couple new servers would make things stable again, but that's way off my budget for this hobby. :)

**Comment by johansolve** [comment]
Ok thanks! Understandable.
