### ISSUE TITLE
$GOPATH/bin/freegeoip Serves files from current dir

### ISSUE THREAD

**Issue by danathesane** [fiorix/freegeoip#154]
I did a fresh install following the install directions at the bottom of the page (i.e. not Docker). I noticed that when I ran the freegeoip command and loaded localhost:8080 in my browser, I got a directory listing for the folder I ran the command from. The old version I was using (3.0.4) returned HTTP 404.

The old behaviour would help prevent peoples files from being exposed over the web.

**Comment by fiorix** [comment]
Done.

**Comment by danathesane** [comment]
Thanks!
