### ISSUE TITLE
go get doe not download dependencies

### ISSUE THREAD

**Issue by zechnkaas** [fiorix/freegeoip#156]
Hi,

short notice the "go get -d github.com/fiorix/freegeoip" does not download the dependencies since 3.0.10 (windows) after manually downloading them the build work again (Windows)

> github.com/fiorix/go-redis/redis
> github.com/gorilla/handlers
> github.com/prometheus/client_golang/prometheus
> golang.org/x/net/http2

maybe you change it that it works again or add it to the tutorial 
ty

**Comment by fiorix** [comment]
Thanks!
