### ISSUE TITLE
Docker container shows directory contents

### ISSUE THREAD

**Issue by schmunk42** [fiorix/freegeoip#157]
When I run the `:latest` Docker image, I can browse most parts of the webroot.

```
public/
ansible-playbook/
wrk-test.lua
release.sh
main.go
```

`/json` and `/public` URLs still work as expected, but older versions have shown a `404`.

Could you also set up automatic tagging of the Docker images, please?

**Comment by fiorix** [comment]
Docker hub shows `:latest` as being from yesterday. I manually triggered another build there but I suspect you need a pull? You can do `run ... -version` to confirm.

**Comment by schmunk42** [comment]
Thank you, I had some different images in my swarm. What's about setting up automated tags for Docker images?

**Comment by fiorix** [comment]
It is there. Under the project's Build Settings: Type=branch, Name=master, TagName=latest.

**Comment by schmunk42** [comment]
I mean more like so (2nd row):

<img width="1282" alt="bildschirmfoto 2016-02-02 um 16 38 26" src="https://cloud.githubusercontent.com/assets/649031/12754419/6fb8ceaa-c9cb-11e5-9e6d-55ddef15c22a.png">

This would create `fiorix/freegeoip:3.0.10`, `fiorix/freegeoip:3.0.11`, ...

**Comment by fiorix** [comment]
Ah, sure. Done. But now I don't know how to easily trigger these tag based builds.

**Comment by schmunk42** [comment]
It's just the setting in the backend, I even think it's the new default.
They updated it around 2-3 months ago, AFAIR - see also https://docs.docker.com/docker-hub/builds/

Set it up once and your GitHub tags are used for Docker Hub images, as simple as that.

**Comment by fiorix** [comment]
Yeah I get it, very useful. But as of now such images with the versioned tags don't exist, and will be built when pushed to git.
