### ISSUE TITLE
Server returned HTTP 503: Try again later

### ISSUE THREAD

**Issue by Scripore** [fiorix/freegeoip#159]
I'm using the geocoder gem and have been getting this error message:
`geocoding API error: 503 Service Unavailable`
`Geocoding API's response was not valid JSON: Try again later`

On freegeoip.net, I'm getting `Server returned HTTP 503: Try again later` half the time. Is it because the server is under heavy load or something else?

**Comment by hookenz** [comment]
Getting the same issue.

**Comment by fiorix** [comment]
Looking at the stats there's a lot more SSL than an average day and the servers are running out of capacity. I don't have more budget to add new servers so if you're using it in production I'd recommend you roll out your own servers. Sorry.

**Comment by lasernite** [comment]
+1 happening again. Any easy solutions for light-production?

**Comment by fiorix** [comment]
Yeah my servers just can't handle the amount of traffic coming in. And I have no more budget for this.

http://i.imgur.com/NJ7ka1s.png

**Comment by hookenz** [comment]
@lasernite - Roll your own.  @fiorix provides a docker image you can use straight.  It works really well!

**Comment by lasernite** [comment]
Are you considering putting up something like a $1 /month paywall? It would have the simultaneous effect of eliminating > 90% of the traffic which is probably spam, like what made Telize shut down their public version, and it would guarantee revenue to cover the server costs?

**Comment by lasernite** [comment]
@hookenz thanks I'll look into that, just has been nice to have totally hands off, just using the [geocoder](https://github.com/alexreisner/geocoder) gem.

**Comment by fiorix** [comment]
@lasernite Yes I am.

**Comment by fiorix** [comment]
fwiw the geocoder gem supports custom hosts https://github.com/alexreisner/geocoder#freegeoip-freegeoip
