### ISSUE TITLE
cannot unmarshal DNS Message

### ISSUE THREAD

**Issue by hookenz** [fiorix/freegeoip#160]
I'm getting this error when using your docker container.

[freegeoip] 2016/02/16 21:21:33 database error: download failed (will retry in 2s): Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz: dial tcp: lookup geolite.maxmind.com on 192.168.0.1:53: cannot unmarshal DNS message

Could be related to this.  Maybe mindmax has made some DNS changes.
https://github.com/golang/go/issues/11070

**Comment by fiorix** [comment]
I get a different error using the `:latest` docker image:

    [freegeoip] 2016/02/17 03:56:32 database error: download failed (will retry in 2s): Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz: dial tcp: lookup geolite.maxmind.com on 10.0.1.1:53: read udp 172.17.0.2:44585->10.0.1.1:53: i/o timeout


Also related to DNS. Mmmm.

**Comment by fiorix** [comment]
Never mind, my issue above was related to a misconfigured DNS in boot2docker. The `:latest` image does work for me:

    $ docker run --rm -it fiorix/freegeoip
    [freegeoip] 2016/02/17 04:01:16 freegeoip http server starting on :8080
    [freegeoip] 2016/02/17 04:01:50 database loaded: /tmp/freegeoip/db.gz

This might be something on your end.

**Comment by hookenz** [comment]
Could have been.  I've literally just changed service providers from yesterday so I'm using different DNS servers.  The error has gone away.  Odd.
