### ISSUE TITLE
How could you support language detect?!

### ISSUE THREAD

**Issue by dotku** [fiorix/freegeoip#161]
Is there anyway to force the return by specified language?

**Comment by fiorix** [comment]
Yes, by setting the `Accept-Language` header in the request.

Example:

    $ curl -s freegeoip.net/csv/rutube.ru
    91.207.59.161,RU,Russia,,,,,,55.75,37.62,0

    $ curl -s -H 'Accept-Language: ru' freegeoip.net/csv/rutube.ru
    91.207.59.161,RU,Россия,,,,,,55.75,37.62,0

**Comment by dotku** [comment]
Is it passable done by the client side such as ·freegeoip.net?lang=zh·

**Comment by fiorix** [comment]
No, only via header.

**Comment by dotku** [comment]
I'm have working on this project for a month, it is done by mins right now!
Cool~!

Your data is better then commerical~!
Just buy you a coffee and thanks :+1:
