### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by sigmadan** [fiorix/freegeoip#162]
![screen shot 2016-02-24 at 11 24 57 am](https://cloud.githubusercontent.com/assets/11512873/13294404/6944a696-dae9-11e5-83d6-9f340490f13a.png)
![screen shot 2016-02-24 at 11 25 59 am](https://cloud.githubusercontent.com/assets/11512873/13294405/694f961e-dae9-11e5-9173-4d69805615d0.png)

**Comment by fiorix** [comment]
Servers overloaded, there's no much I can do at this point.

I recommend you to download the freegeoip web server from https://github.com/fiorix/freegeoip/releases and deploy on your server.

**Comment by jhg-tgu** [comment]
Same error only with custom pay DB

**Comment by sigmadan** [comment]
@jhg-tgu - We ended up deploying on our own AWS elastic server, and haven't had an issue since.
