### ISSUE TITLE
Use referral IP instead of specifying? (feature request)

### ISSUE THREAD

**Issue by joakim1** [fiorix/freegeoip#163]
Can it be possible to not specify an IP and instead check for requester's IP?  
Example: `freegeoip.net/json/referer`

**Comment by fiorix** [comment]
That's the default behavior.

This:

    curl freegeoip.net/json/

Will lookup your own IP. Note the trailing slash.

**Comment by nicooprat** [comment]
Just figured it out myself, would be interesting to write it on the homepage!

**Comment by fiorix** [comment]
This information is already there.

**Comment by nicooprat** [comment]
Read it twice, indeed there's this tiny sentence "If no IP or hostname is provided, then your own IP is looked up". But the example code above doesn't look like the second parameter is optional (Github README is clearer IMO) and my brain didn't go further. Just saying! Thanks for your work anyway :)
