### ISSUE TITLE
[Docker] - Connection refused

### ISSUE THREAD

**Issue by alfredtan** [fiorix/freegeoip#164]
Hi,

I ran this: `docker run -d -p 8080:8080 fiorix/freegeoip` and I can see the container running when I run `docker ps`. 

But when I call the service, I get connection refused:
`[~]$ curl 0.0.0.0:8080/`
`curl: (7) Failed to connect to 0.0.0.0 port 8080: Connection refused`
`[~]$ curl localhost:8080`
`curl: (7) Failed to connect to localhost port 8080: Connection refused`
`[~]$ curl $(docker-machine ip default):8080`
`curl: (7) Failed to connect to 192.168.99.100 port 8080: Connection refused`

I can call the service if i'm inside the container though. 

Any tips on getting the port mapping working?

**Comment by fiorix** [comment]
I think because the default http listen address is set to localhost:8080 it is only binding to IPv6. Let me push an update that binds to :8080 by default and it should work.

**Comment by alfredtan** [comment]
Thanks for this!

**Comment by fiorix** [comment]
Docker is building the new image, once ready you can try `docker pull fiorix/freegeoip` and run again, should work.

**Comment by alfredtan** [comment]
Awesome, i'll wait a bit and do that.

**Comment by fiorix** [comment]
Just tested, works as expected. Have fun! :)

**Comment by alfredtan** [comment]
It works for me too! I was testing your service using 2 containers, freegeoip being one of them. 

Thanks again.

**Comment by fiorix** [comment]
Just so you know you can pass `--internal-server=:8888` to run a local web server that provides service metrics under ip:8888/metrics about requests, and the origin of visitors using the service. This is not yet documented anywhere and I use for for monitoring my production services. If you have http://prometheus.io you can point it to this internal server and get some nice graphs.

**Comment by alfredtan** [comment]
Nice. That's good info. i've never used prometheus, but i'll give it a go.
