### ISSUE TITLE
How to run freegeoip on Windows

### ISSUE THREAD

**Issue by willcun** [fiorix/freegeoip#166]
Help...

I have installed Go and Git within Windows 7.  I used the below commands from github:

go get -d github.com/fiorix/freegeoip/...
go install github.com/fiorix/freegeoip/cmd/freegeoip

How do I get the webserver to run?  Are there any instructions for Windows?

**Comment by fiorix** [comment]
I've never tried on Windows, but once the server is built you can just execute it. It will be in `$GOPATH/src/github.com/fiorix/freegeoip/cmd/`, a file called `freegeoip.exe`.

**Comment by willcun** [comment]
Thanks for the quick response!!!  

I have the src directory but there is no file named freegeoip.exe.  How do I go about getting that file?

**Comment by fiorix** [comment]
ok, I think my reply above wasn't very accurate. Because you did `go install`, the binary will be places under `$GOPATH/bin/freegeoip.exe`.

**Comment by willcun** [comment]
Fiorix,

I'm not trying to be a nuisance and I see you closed this but now that I have gotten freegeoip.exe I am still getting "404 page not found".  (Firewalls turned off and all ports are wide open)... It starts on port 8080 and downloads the DB but if I use Chrome or any other browser to http://localhost:8080 or http://x.x.x.x:8080 its "404 page not found"  

I would really like to get this to work and if you can help it would be greatly appreciated.  I'm not as proficient with Linux as I am with Windows.

**Comment by fiorix** [comment]
It is working. You get 404 because you didn't pass the -public option to make it serve the site. If you query /json/ip it will return data.

**Comment by willcun** [comment]
Fiorix,

Thanks again man for the quick response and please don't think I'm an imbecile but I have added the -public:

From command prompt "freegeoip -public www.stayawayhaters.com"...  It starts, loads the database but when I query from an outside source with "www.stayawayhaters.com:8080" or "www.stayawayhaters.com/json/ip:8080" or "www.stayawayhaters.com/json/x.x.x.x:8080"  I still get 404 errors.  Please try the www.stayawayhaters.com for yourself.  Its an actual site of mines.  It tells you your current IP Address.  I use port forwarding for 8080 that runs freegeoip on another box.  

I have Verizon Fios and when I enter my WAN IP into other GeoLocation Sites it they tell me everything about my WAN IP

**Comment by fiorix** [comment]
Hey I'm not judging, only trying to help, for real. The -public option should point to a directory on your machine, which contains index.html and related files. If your www.stayawayhaters.com is a directory, in your current directory, then there is something wrong. Is that the case?

**Comment by willcun** [comment]
Fiorix... Man that did it!!!  I'm up and running!!!  THX MAN!!!  :-)

Man this is nice!!!

**Comment by fiorix** [comment]
lol :+1:
