### ISSUE TITLE
Malformatted JSON causing error with Geocoder

### ISSUE THREAD

**Issue by arnlen** [fiorix/freegeoip#167]
The returned JSON surprises me, because the payload is enclosed by parenthesis:

```
({"ip":"90.34.122.47","country_code":"FR","country_name":"France","region_code":"O","region_name":"Nord-Pas-de-Calais","city":"Lumbres","zip_code":"62380","time_zone":"Europe/Paris","latitude":50.7069,"longitude":2.1208,"metro_code":0});
```

This causes error with the Ruby [Geocoder gem](https://github.com/alexreisner/geocoder):

```
Geocoding API's response was not valid JSON: ({"ip":"90.34.122.47","country_code":"FR","country_name":"France","region_code":"O","region_name":"Nord-Pas-de-Calais","city":"Lumbres","zip_code":"62380","time_zone":"Europe/Paris","latitude":50.7069,"longitude":2.1208,"metro_code":0});
```

How could I get a raw JSON from the API?

**Comment by fiorix** [comment]
Looks like you're hitting the JSONP one, `/json/90.34.122.47` vs `/json/90.34.122.47?callback=f`

**Comment by tidyware** [comment]
It looks like the JSON API endpoint is returning JSONP when it shouldn't be.

**Comment by fiorix** [comment]
Nop, can't be.

**Comment by profeg** [comment]
freegeoip.net is down now.  
Available freegeoip.io
