### ISSUE TITLE
CORS disabled in 3.1.x 

### ISSUE THREAD

**Issue by davidlgj** [fiorix/freegeoip#168]
Hi,

it seems like CORS has been disbled in version 3.1.0 and upwards.By default I get no CORS headers at all and when trying the binary releases (on linux) the flag `-cors-origin` doesn't seem to change anything. Is this by design?

Awesome server btw, fast and so simple to get up and running :clap: Thanks!

**Comment by fiorix** [comment]
Hi David,

CORS is there. Version 3.1.0 is when I switch from my own implementation over to https://github.com/rs/cors. Just tested here, it works. Are you having troubles?

**Comment by davidlgj** [comment]
Hi @fiorix and thank you for asnwering! 

This is what I tried.
* cloned this repo and started a docker instance with `docker run --net=host --restart=always -d fiorix/freegeoip`
* started via binary release instead, `./freegeoip -http :9000`
* started via binary with -cors-origin flag, ./freegeoip -cors-origin "*" -http :9000

In all three cases I can't see any CORS headers, neither in the browser nor via curl. This is what I get:
```
~/Hämtningar/freegeoip-3.1.4-linux-amd64$ curl -i localhost:9000/json/1.2.3.4
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Origin
X-Database-Date: Wed, 30 Mar 2016 12:49:49 GMT
Date: Wed, 30 Mar 2016 12:52:58 GMT
Content-Length: 242

{"ip":"1.2.3.4","country_code":"US","country_name":"United States","region_code":"WA","region_name":"Washington","city":"Mukilteo","zip_code":"98275","time_zone":"America/Los_Angeles","latitude":47.913,"longitude":-122.3042,"metro_code":819}
```

Is there something else I can try? How can I help?

**Comment by fiorix** [comment]
It is correct, the `Vary` header is present. See the link above for details.

**Comment by davidlgj** [comment]
Ok, maybe I missed something, but which link?

**Comment by fiorix** [comment]
The one with the CORS implemented used in freegeoip. https://github.com/rs/cors

**Comment by davidlgj** [comment]
Could you be more specific on what part of that README.md you mean? I'll read up on the specification. 

Doing an ordinary ajax request works in 3.0.x but not in 3.1.x,  so do I need to change something?

**Comment by davidlgj** [comment]
AFAIK `Vary: origin` means that the the cache policy should be domain specific. You still need `Access-Allow-Origin` headers to be set and no such headers are set, as you can see in my curl output above. 

So I guess my question is how do I get  a `Access-Allow-Origin: *` header?

**Comment by fiorix** [comment]
You will only get that header when an Origin is passed on the request. I have just tested by running a freegeoip server on a remote machine and the front-end on a local web server. Ajax requests work just fine. Are you getting an error on your browser?

**Comment by davidlgj** [comment]
Yes, my code broke when updating freegeoip version. In this case I was using the Angular JS $http service, which uses jQuery underneath. 

I'll debug and check what headers etc it sends (I believe it first does an OPTIONS request), and I'll also try a "vanilla"  XMLHttpRequest. Thank you again for helping me here.

**Comment by fiorix** [comment]
The front-end code also uses Angular, and is what I tested.

You can change L48 of https://github.com/fiorix/freegeoip/blob/master/cmd/freegeoip/public/index.html to point to a remote server.

**Comment by davidlgj** [comment]
We'll this is embarrassing... it was our own setup that broke it. 

**I'm so sorry for taking up your time.** And thank you for all your help!

**Comment by fiorix** [comment]
No problem :)
