### ISSUE TITLE
Deploying to own server with SSL

### ISSUE THREAD

**Issue by DanielStevenLewis** [fiorix/freegeoip#169]
Hey guys, I'm having trouble deploying to my server with ssl/https. It works fine over http, but when I do 'sudo docker run --net=host --restart=always -d fiorix/freegeoip -cert "something.crt" -key "something.key" -https ":8080"' and try to "curl https://My_URL:8080/json/", it outputs "Unknown SSL protocol error in connection to My_URL:8080" on my laptop, or "curl: (7) Failed to connect to localhost port 8080: Connection refused" on the server itself . I know that my .crt and .key files are correct because nginx is working properly with them on the same server. Any ideas?

**Comment by fiorix** [comment]
If you don't disable the http server, it will listen on :8080 by default. You can test on your local machine by first creating a self-signed key pair, e.g.:

```
go run $GOROOT/src/crypto/tls/generate_cert.go --host=localhost
```

Then running the container:

```
docker run --rm -v `pwd`:/tmp/fs -p 8080:8080 -it fiorix/freegeoip -http="" -https=:8080 -cert=/tmp/fs/cert.pem -key=/tmp/fs/key.pem
```

**Comment by DanielStevenLewis** [comment]
Thanks fiorix. When I run that second command you posted (with my already existing cert and key) it outputs 
freegeoip https server starting on :8080
open /etc/ssl/something.crt: no such file or directory

/etc/ssl/something.crt does exist though

**Comment by fiorix** [comment]
It has to exist inside the container. Perhaps you're missing the `-v` flag for docker?

**Comment by DanielStevenLewis** [comment]
-v flag's there

**Comment by fiorix** [comment]
Is your certificate readable by the freegeoip process, is it in PEM format? When you run in foreground (`--rm -it`), do you get any errors?

**Comment by DanielStevenLewis** [comment]
Yes to all I believe. Same error when I run it in the foreground. As a test I tried copying the cert and key to a new temporary folder and did chmod -R 777 on the root of the folder, so it should be readable after that at least.

**Comment by fiorix** [comment]
Can you paste the errors?

**Comment by DanielStevenLewis** [comment]
myusername@servername:/$ sudo chmod -R 777 /tmp2
myusername@servername:/$ sudo docker run --rm -it fiorix/freegeoip -cert=/tmp2/fs/something.crt -key=/tmp2/fs/servername.key -http="" -https=:8080
2016/04/01 16:21:42 freegeoip https server starting on :8080
2016/04/01 16:21:42 open /tmp2/fs/something.crt: no such file or directory
myusername@servername:/$ ls /tmp2/fs
something.crt  servername.key
myusername@servername:/$ sudo chmod -R 000 /tmp2

**Comment by fiorix** [comment]
This is the problem I mentioned earlier. When you run my docker image fiorix/freegeoip, it does not have your certificate in it. You have to use the `-v` option to mount your local directory with the certificates inside the container, so the freegeiop process can access it.

**Comment by DanielStevenLewis** [comment]
That's what I tried before.

myusername@servername:/$ sudo docker run --rm -v `pwd`:/tmp2/fs -p 8080:8080 -it fiorix/freegeoip -cert=/tmp2/fs/something.crt -key=/tmp2/fs/something.key -http="" -https=:8080
docker: Error response from daemon: failed to create endpoint elated_carson on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.
myusername@servername:/$ sudo docker run --rm -v `pwd`:/tmp2/fs -p 59485:59485 -it fiorix/freegeoip -cert=/tmp2/fs/something.crt -key=/tmp2/fs/something.key -http="" -https=:59485
2016/04/01 16:54:32 freegeoip https server starting on :59485
2016/04/01 16:54:32 open /tmp2/fs/something.crt: no such file or directory


For some reason it's giving me a different error message today that it was yesterday when I used 8080. Don't know why. Yesterday when I ran the first command (with 8080) it instead outputted: 
open /tmp2/fs/something.crt: no such file or directory

**Comment by DanielStevenLewis** [comment]
Perhaps I misunderstood one thing you said though. I thought you were saying that to run it in the foreground you use the same command but remove the stuff ("-v `pwd`:/tmp2/fs -p 8080:8080") between "--rm" and "-it".

**Comment by groovezog** [comment]
@DanielStevenLewis Did you ever figure this out? If you remember what did the trick, I'm trying to do the same thing.

**Comment by DanielStevenLewis** [comment]
Nope. If you figure out please let me know.
