### ISSUE TITLE
No Access-Control-Allow-Origin ..

### ISSUE THREAD

**Issue by cullsin** [fiorix/freegeoip#172]
Hi, 

I getting the below error 

          XMLHttpRequest cannot load http://freegeoip.net/json/. No 'Access-Control-Allow-Origin' header is            present on the requested resource. Origin 'http://anaoh.com' is therefore not allowed access.

I am calling like this, 

         $.ajax({ "url" : "http://freegeoip.net/json/", "headers" : { "Access-Control-Allow-Origin" : "*" } })
         .done(function (data) { }

Can you please suggest me what went wrong ? It was worked yesterday.

Raja K

**Comment by fiorix** [comment]
If you pass the `Origin` header you get what you're looking for. Without passing that header you just get `Vary: Origin` in the response.

Example without origin:

```
$ curl -i freegeoip.net/json/4.2.2.2
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Origin
X-Database-Date: Tue, 17 May 2016 08:42:57 GMT
X-Ratelimit-Limit: 10000
X-Ratelimit-Remaining: 9998
X-Ratelimit-Reset: 3597
Date: Wed, 25 May 2016 15:07:23 GMT
Content-Length: 194
```

With origin:

```
$ curl -i -H "Origin: http://example.com" freegeoip.net/json/4.2.2.2
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://example.com
Content-Type: application/json
Vary: Origin
X-Database-Date: Tue, 17 May 2016 08:42:57 GMT
X-Ratelimit-Limit: 10000
X-Ratelimit-Remaining: 9997
X-Ratelimit-Reset: 3572
Date: Wed, 25 May 2016 15:07:48 GMT
Content-Length: 194

{"ip":"4.2.2.2","country_code":"US","country_name":"United States","region_code":"","region_name":"","city":"","zip_code":"","time_zone":"","latitude":37.751,"longitude":-97.822,"metro_code":0}
```

**Comment by cullsin** [comment]
Hi, 

I am getting 405 "Method not allowed" error message. I guess jquery sending pre-flight "Options" request before sending an actual "GET" request. 

How do I skip that "OPTIONS" ?

Raja K

**Comment by fiorix** [comment]
See #170.
