### ISSUE TITLE
Postal Codes with spaces don't write properly

### ISSUE THREAD

**Issue by brigzzy** [fiorix/freegeoip#173]
I notices that when I geocode an IP address that contains a space, the postal code gets cut off.  I think that if the space character was replaced with an underscore, or something similar, this would work better.

**Steps to reproduce**

1. Curl an IP address hosted in Canada:

`curl 1.2.3.4:8080/csv/pscnaturalfoods.com`
2. Note the output for the postal code:

204.174.230.6,CA,Canada,BC,British Columbia,Victoria,**V8Z**,America/Vancouver,48.50,-123.40,0

**Comment by fiorix** [comment]
That comes straight from the database, which only has the first part of the postal code (at least in the free db version).
