### ISSUE TITLE
restricted access for self-hosting

### ISSUE THREAD

**Issue by fiorix** [fiorix/freegeoip#174]
Hey @dheian let's track your issue from here.

**Comment by fiorix** [comment]
There are different ways of restricting access to your self-hosted server. If your clients are mostly browsers, you can configure the server to only accept requests from pages served from your own domain, by using the `-cors-origin` cmdline flag.

**Comment by xtian88** [comment]
Hey @fiorix is there also an easy way to restrict access using a user + pw authentication for the json api?

**Comment by fiorix** [comment]
No, but you can use nginx with auth and any other config in front of it.

**Comment by dheian** [comment]
@fiorix,

Thanks. I  know I have to read up more on Docker, but if I rerun the freegeoip Docker command with -cors-origin added, does that update the currently running instance?

**Comment by fiorix** [comment]
It doesn't, you have to restart it.
