### ISSUE TITLE
Problems with deploying freegeoip on my server using Docker. 

### ISSUE THREAD

**Issue by epezhman** [fiorix/freegeoip#175]
Hi, thank you very much for the great code. I have never used `Docker ` and I need some help please. I have a Debian 8 as a server on DigitalOcean and I'm using Nginx (Nginx runs on the same server as my freegeoip). I installed the Docker and the freegeoip and everything seems working fine and I have access to it from remote on port 8080. I need to change my port and also set the -`use-x-forwarded-for` but it seems not working. 

First I try to set the port like this:

```
epezhman@debian-dm:~$ docker run --rm -it fiorix/freegeoip -http=127.0.0.1:2501
2016/07/07 16:43:51 freegeoip http server starting on 127.0.0.1:2501
2016/07/07 16:43:53 database loaded: /tmp/freegeoip/db.gz
```
but still I have access to it from `:8080` instead of  `:2501`

and I configured my Nginx like this 

```
 location /freegeoip/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr;
   }
```

and I'm not sure how to set the ` -use-x-forwarded-for`:

`sudo docker run --rm -it fiorix/freegeoip -user-x-forward-for=true
`

**Comment by fiorix** [comment]
You just pass the flag, the `=true` part is redundant.

```
docker run --rm -it fiorix/freegeoip -http=127.0.0.1:2501 -use-x-forwarded-for
```

**Comment by fiorix** [comment]
Also you'll need -p on docker cmdline to bind ports to the host.

**Comment by epezhman** [comment]
@fiorix Thanks for the comment. I could not run it in a way you mentioned but I found a workaround, I'm writing it here in the case someone with little Docker experience faces the same problem:

So, if you want to run Freegeoip on your server behind the Nginx, you need to follow these steps (I have little experience with either Docker or Nginx, although this works for me it may not be the best solution)

1 - Check if you are already running a `container `of Freegeiop:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
c603d0eedef9        fiorix/freegeoip    "/go/bin/freegeoip -h"   9 minutes ago       Up 9 minutes                            dreamy_volhard
```
2 - If yes, then you need to first stop, then remove the container (find the container's name from `docker ps`, don't use dreamy_volhard on your machine):
```
$ docker stop dreamy_volhard
dreamy_volhard
$ docker rm dreamy_volhard
dreamy_volhard
```
3 - Now you can run the container again on for Nginx with desired IP and port, I needed 127.0.0.1:2501:

```
docker run --net=host --restart=always -d fiorix/freegeoip -http=127.0.0.1:2501 -use-x-forwarded-for
```

4 -The Nginx configuration could be something like this: 

```
 location /freegeoip/ {
        proxy_pass http://127.0.0.1:2501/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr;
   }
```

5 - After restarting the Nginx service you can have access to Freegeoip from some address like this `your-domain/freegeoip/json`
