### ISSUE TITLE
httpoxy vulnerability in freegeoip server?

### ISSUE THREAD

**Issue by apotek** [fiorix/freegeoip#177]
According to the advisory here https://httpoxy.org/, Go web applications that hand off requests to other servers may be vulnerable to this HTTP_PROXY attack if they use the net/http/cgi library.

> What Is Affected
> 
> A few things are necessary to be vulnerable:
> 
>    * Code running under a CGI-like context, where HTTP_PROXY becomes a real or emulated environment variable
>    * An HTTP client that trusts HTTP_PROXY, and configures it as the proxy
>    * That client, used within a request handler, making an HTTP (as opposed to HTTPS) request
> 
> For example, the confirmed cases we’ve found so far:
> Language 	Environment 	HTTP client
> PHP 	php-fpm, mod_php 	Guzzle 4+,Artax
> Python 	wsgiref.handlers.CGIHandler, twisted.web.twcgi.CGIScript	requests
> Go 	net/http/cgi 	net/http

I note that freegeoip imports 
```
import (
	"flag"
	"fmt"
	"log"
	"net"
"net/http"
```

Can we confirm whether the freegeoip server needs an update in order to mitigate any concerns from HTTP_PROXY based attacks?

**Comment by fiorix** [comment]
Not the case here.
