### ISSUE TITLE
Problem installing SSL cert on my own server

### ISSUE THREAD

**Issue by groovezog** [fiorix/freegeoip#180]
I've been running freegeoip successfully on a DigitalOcean server for a few months over HTTP, on port :9090. I have an SSL certificate to install but I'm getting an error after running: 
`docker run --rm -v `pwd`:/tmp/fs -p 9090:9090 -it fiorix/freegeoip -http="" -https=:9090 -cert=/tmp/fs/www_example_com.crt -key=/tmp/fs/example.com.key`
The error is:
`[error] 2016/08/04 23:03:10 http: TLS handshake error from xxx.xxx.xxx.xxx:57122: tls: first record does not look like a TLS handshake`
I'm pretty sure that the .CRT and .KEY files are in PEM format (the begin with -----BEGIN). I've verified that my .CRT and .KEY files match.

**Comment by fiorix** [comment]
This error seems like you're using an http client to connect to an https server.
