### ISSUE TITLE
Fallback Public API

### ISSUE THREAD

**Issue by turbo** [fiorix/freegeoip#182]
Since we have some free resources to spare, we can provide a fallback API URL. A daemon regularly checks our servers for free bandwidth and allocates as much as possible to this API (100Mbps egress maximum). This is JSON only.

The base URL is `https://labs.turbo.run/api/v1/misc/geo`. It accepts one parameter, `host`. This is either a hostname or IP. It returns "pretty" JSON.

**Example**

Request

```
https://labs.turbo.run/api/v1/misc/geo?host=example.com
```

Answer

``` json
{
    "ip": "2606:2800:220:1:248:1893:25c8:1946",
    "country_code": "US",
    "country_name": "United States",
    "region_code": "",
    "region_name": "",
    "city": "",
    "zip_code": "",
    "time_zone": "",
    "latitude": 39.76,
    "longitude": -98.5,
    "metro_code": 0
}
```

Any error either results in `null` or, very rarely, a timeout.

**Comment by fiorix** [comment]
This is cool, thanks. Will keep the issue open so others can find it.

**Comment by turbo** [comment]
cc @scottpcrawford

The URL changed. More resources are now available and the response time should be much faster. Also, the full API is enabled now. Use `antiquant.com` like usual. Example:

`http://antiquant.com:8080/json/example.com`

```text
{"ip":"93.184.216.34","country_code":"US","country_name":"United States","region_code":"MA","region_name":"Massachusetts","city":"Norwell","zip_code":"02061","time_zone":"America/New_York","latitude":42.1508,"longitude":-70.8228,"metro_code":506}
```

This API is HTTP only for now.

**Comment by Krishna-teja** [comment]
@turbo The url doesnt seem to be working?

**Comment by fiorix** [comment]
No longer working.
