### ISSUE TITLE
[FR] Add timezone UTC time offset / local time

### ISSUE THREAD

**Issue by Gamadril** [fiorix/freegeoip#184]
Not an issue, but a feature request...
Timezone information is good, but it would be also useful to get the UTC time offset directly like +2:00
The best would be of course to get the local time directly evtl. considering the daylight saving time. 😄

**Comment by fiorix** [comment]
There's no algorithm for this, governments change at will. This is why we only return the timezone name, not the offset. You have to get the offset elsewhere.

Sorry but this is not happening. For the record, we had this in the API back in the days (maybe in 2010, 2011) and it was removed.
