### ISSUE TITLE
Interest in adding MaxMind's accuracy_radius to results?

### ISSUE THREAD

**Issue by johndburger** [fiorix/freegeoip#185]
Hi, this is more of a question. At least partly in response to this issue:

http://fusion.net/story/287592/internet-mapping-glitch-kansas-farm/

MaxMind has apparently added an `accuracy_radius` field to their GeoIP2 data. Is their any interest in adding this to at least the XML and JSON results returned by freegeoip? I'm not a Go programmer, so I'd like to know whether a PR with this addition is likely to be accepted before I invest in figuring out how to do it.

Thanks.

**Comment by nodesocket** [comment]
👍  the more we can return from MaxMind they better. Does ISP or ORGANIZATION come back from teh free data by chance?

**Comment by fiorix** [comment]
@nodesocket ISP and ORG are different dbs

**Comment by fiorix** [comment]
I thought I had replied to this, my bad. I will be happy to review any PR with this change.

**Comment by fiorix** [comment]
This doesn't seem to be going anywhere, closing.

**Comment by cowai** [comment]
Would this also work with the geolite databases?
