### ISSUE TITLE
Make it possible to read use an uncompressed database

### ISSUE THREAD

**Issue by J5lx** [fiorix/freegeoip#186]
My distributions package of the database provides only the gunzip’ed .mmdb file, and of course I'd like the freegeoip server to use it instead of having a 30M file downloaded after every reboot. From a quick glance at the code it seems that this should be rather easy to implement, but then again I’m not exactly a Go expert (I tried to do it myself but apparently my trial-and-error skills are not sufficient here). I’d appreciate it if you could help me out.

**Comment by fiorix** [comment]
You can set the `TMPDIR` environment variable to change the location where the db is downloaded, and point to a directory that will survive reboots. e.g. `TMPDIR=/var/tmp freegeoip -params...`.

If you want to manage the file yourself, you can easily gzip your mmdb before replacing the old one to be picked up by freegeoip. It's not hard to support uncompressed files, but I can't do now. Will leave this issue open for now.

**Comment by J5lx** [comment]
Ah, thanks a lot! The `TMPDIR` variable is not the most elegant solution but it does work quite well indeed. I like it much better than manually gzipping the file since it doesn't require manual intervention.

**Comment by f0ster** [comment]
@J5lx I have a fix for this here, https://github.com/fiorix/freegeoip/pull/215

**Comment by fiorix** [comment]
no updates here, closing
