### ISSUE TITLE
GEO is a little funky

### ISSUE THREAD

**Issue by dchimvp** [fiorix/freegeoip#188]
Hello, I have an issue in one of our cities that we are geo targeting, it works in others, but for some reason not this city.

I have a sales rep in Columbus, OH and we have particular content for there, but when they go on the site, it doesn't show Columbus content that should be showing.  

I had them go on "whatsmyip.com" and it shows they are in columbus, but yet it is not showing the content.  

Do you know what the issue could be?

**Comment by fiorix** [comment]
Sounds like bad entry in the database. You can submit corrections directly to MaxMind.

**Comment by dchimvp** [comment]
can you do by postal code and state instead of city and state?

**Comment by fiorix** [comment]
Do what, exactly? Queries are only by IP, and things like state and city are in the response - if they are in the database.
