### ISSUE TITLE
API: Region not accurate

### ISSUE THREAD

**Issue by Baldoius** [fiorix/freegeoip#190]
When using the tool it displays "Buchs" (Switzerland), what's actually correct!
But the displayed region is "Canton Zurich", and that's wrong!
I guess that's happening because there are existing 2 Buchs, once in Canton Zurich and once in St. Gallen.

Happens only when using your API, works on freegeoip.net

**Comment by fiorix** [comment]
You can submit corrections directly to MaxMind, there's nothing we can do from here.
