### ISSUE TITLE
Get metrics

### ISSUE THREAD

**Issue by jimmyadaro** [fiorix/freegeoip#192]
Hi there;

I'm calling to the API via `curl` like this:

`$ curl freegeoip.net/json/ -internal-server=:8081`

but I need to find the way to get those metrics with PHP for implement it with my [non-commercial] script. I've tried this without success:

`freegeoip.net/json/metrics`

`freegeoip.net/metrics/json`

`freegeoip.net/metrics`

`freegeoip.net/metrics/`

How can I then either provide the URL or (somehow) send the `-internal-server` data as a header or parameter?

Thanks for reading.

**Comment by CyDoor** [comment]
Hello,

im feeling free to answer:
add to the file "config.go" in the apiserver after the lines 
`func NewConfig() *Config {
	return &Config{
		ServerAddr:        ":8080",:`

this:
`InternalServerAddr: ":8081",`

then it should look like this:
`func NewConfig() *Config {
	return &Config{
		ServerAddr:        ":8080",
		InternalServerAddr: ":8081",
		TLSCertFile:       "cert.pem",
		TLSKeyFile:        "key.pem",
		APIPrefix:         "/",
		CORSOrigin:        "*",
		ReadTimeout:       30 * time.Second,
		WriteTimeout:      15 * time.Second,
		DB:                freegeoip.MaxMindDB,
		UpdateInterval:    24 * time.Hour,
		RetryInterval:     2 * time.Hour,
		LogTimestamp:      true,
		RedisAddr:         "localhost:6379",
		RedisTimeout:      time.Second,
		MemcacheAddr:      "localhost:11211",
		MemcacheTimeout:   time.Second,
		RateLimitBackend:  "redis",
		RateLimitInterval: time.Hour,
		UpdatesHost:       "updates.maxmind.com",
		ProductID:         "GeoIP2-City",
	}
}

Now you could start the apiserver and reach the metrics under the port 8081.

Best Regards

**Comment by fiorix** [comment]
Thanks @CyDoor. But in fact, I believe what @jimmyadaro is looking for is just to access the internal server for collecting metrics. There's no need to code for this.

Start the server passing the listen address for the internal server and then use curl to hit the same port:

```
freegeoip -internal-server=:9999
...
curl localhost:9999/metrics
```

**Comment by jimmyadaro** [comment]
Thanks for the replies. 

Why not just `freegeoip.net/json/metrics`?

**Comment by fiorix** [comment]
The `/json` path is served from the API server, and the `metrics` one is only served by the internal server, which should not be exposed to outsiders. They run in different ports.
