### ISSUE TITLE
Wrong Country returned for some Glasgow IP address ranges

### ISSUE THREAD

**Issue by aolivava** [fiorix/freegeoip#196]
Hi,

We are using this freegeoip service in one of our projects and it seems that some access from Glasgow are returning the wrong Country (Netherlands).

For example: https://freegeoip.net/json/94.169.215.4
Result:
{"ip":"94.169.215.4","country_code":"NL","country_name":"Netherlands","region_code":"","region_name":"","city":"","zip_code":"","time_zone":"Europe/Amsterdam","latitude":52.3824,"longitude":4.8995,"metro_code":0}

But if we use this: http://api.wipmania.com/94.169.215.4
Result: GB

Kind regards.
Alberto.

**Comment by fiorix** [comment]
Hi Alberto,

The database used by freegeoip is owned and managed by MaxMind and called GeoLite2. You can submit corrections to them.
