### ISSUE TITLE
Do you have a how it works section?

### ISSUE THREAD

**Issue by epetre** [fiorix/freegeoip#198]
I am wondering how it works and mostly how data is updated.

Then reason I am wondering is that I am not sure how to debug an issue I am having.
When I query freegeoip from a home network, it always get the right city. But when I am on 3g or LTE, it seems to be off. Whenever I get the wrong city, I check with [Maxmind](https://www.maxmind.com/en/locate-my-ip-address) and they often get in right.

**Comment by fiorix** [comment]
Hey @epetre, the way it works is pretty simple: there is a database with ip blocks and locations assigned to them. The system itself does not differentiate between fixed and mobile access. The freegeiop web server downloads the database from maxmind and serves it, updates whenever there's a new version available. It's possible that their api serve a slightly different version of the db.
