### ISSUE TITLE
Wrong IP Location 

### ISSUE THREAD

**Issue by AndreasSchoenle** [fiorix/freegeoip#201]
Freegeoip locates 141.5.11.5 in Dortmund, Germany, while the maxmind city database test locates it correctly in Dresden, Germany. 
Not sure whether this has anything to do with the other issue raised.
http://freegeoip.net/?q=141.5.11.5
https://www.maxmind.com/en/geoip-demo

**Comment by omercnet** [comment]
I'm guessing maxmind use their full (paid) database on their demo site, and this project uses the free database which has some inaccuracies

if you'll check other services you'll also get Dortmund
http://ipinfo.io/141.5.11.5

**Comment by fiorix** [comment]
Yeah and if you look at X-Database-Date you'll see the last update was yesterday. There's no much we can do about it.

**Comment by AndreasSchoenle** [comment]
Thanks for the quick answer. Yes, this makes it very unlikely that freegeoip has anything to do with it (unless there are sub-entries or the like).
The IP is correctly indentified as belonging to the DFN blocks of ip-numbers, just the geographical location is wrong. Or maybe they use reverse DNS lookup as additional info. The IP maps to mpi-cbg.de, which in turn DENIC correctly locates at Dresden.

Anyhow, I guess there is nothing to be done at the moment. Thanks again for clearing it up.

**Comment by fiorix** [comment]
The one thing you could consider is submitting a correction to MaxMind and it'll be available in freegeoip as soon as they release the new db.

**Comment by AndreasSchoenle** [comment]
OK, will do.
