### ISSUE TITLE
accuracy and location change over time

### ISSUE THREAD

**Issue by Pacerier** [fiorix/freegeoip#206]
Which data provider are you using?

Also, is it possible that the physical location of an IP would change *drastically* over time?

**Comment by alvincosio** [comment]
I am also experiencing this. my weather widget is not detecting current location anymore. it gave me the wrong location. this happened 2-3 days ago.

**Comment by fiorix** [comment]
We use MaxMind GeoLite2. The database is downloaded automatically whenever they release it so your best bet is to submit corrections to them.
