### ISSUE TITLE
Support multiple allowed domains with CORS

### ISSUE THREAD

**Issue by apotek** [fiorix/freegeoip#208]
This issue arose from another thread https://github.com/fiorix/freegeoip/issues/170 about enabling CORS. Obviously, freegeoip supports CORS. This issue is about supporting more than one domain with CORS without thereby allowing all (*) requests.

If I start the servers with `-cors-origin *` the server will allow requests from any domain and satisfy the client's security model (chrome and firefox).

If I start the server with `-cors-origin www.mydomain.com` the server will allow requests from the specified domain only and satisfy the client's security model (chrome and firefox).

However, if I want to limit access to the API (ie, not send a \* as allowed origin), but have more than one domain to allow, there seems to be no facility for specifying this. `-cors-origin my.domain.comi my.seconddomain.com` will not work.

The topic of multiple whitelisted domains is here: http://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains

Clearly, CORS is not intended to be used on the server side as a way of fully blocking access to services, and I suppose what I need to do is set a load balancer in front that drops all requests that don't have the correct origin header (though of course this can be spoofed), 

I am wondering if there is something in help documentation output of `docker run --rm -it fiorix/freegeoip --help` I am missing. I would like to be able to set the option like this: 
`-cors-origin *.mydomain1.com *.myseconddomain.com ...` and have the freegeoip then implement   something along the line of: if incoming_request_origin is in the passed list of -cors-origins, then return header access-control-allows-origin: incoming_request_origin 

For example, this is one way I could allow a list of whitelisted domains in nginx:

```
$http_origin = $_SERVER['HTTP_ORIGIN'];

if ($http_origin == "http://www.domain1.com" || $http_origin == "http://www.domain2.com" || $http_origin == "http://www.domain3.info")
{  
    header("Access-Control-Allow-Origin: $http_origin");
}
```

Or, in something like php, one could do:

```
if (in_array($HTTP_ORIGIN, $listofcorsalloweddomains)) {
  header("Access-Control-Allow-Origin: $HTTP_ORIGIN");
}
```
When I look at the config structure in the freegeoip code, it looks like it was built with -cors-origin as a string value only, not as an an array, and I see no place where it would be broken into a list of domains or origins, which is why I assume it's not possible.

**Comment by fiorix** [comment]
This is not supported today but is easy to implement. Here: https://github.com/fiorix/freegeoip/blob/master/apiserver/api.go#L52

Split that `c.CORSOrigin` by comma to effectively allow `-cors-origin=domain.foo,domain.bar` from the command line. Please document that in the README :)

**Comment by apotek** [comment]
Thank you @fiorix . I was going to attempt this myself and was doing some web searches to do so, but you beat me to it, and I appreciate your responsiveness. It looks like this is now in latest release. 👏  thank you .
