### ISSUE TITLE
Change shown version from 3.1.5 to 3.2.0

### ISSUE THREAD

**Issue by zechnkaas** [fiorix/freegeoip#209]
Thanks for this release. the only thing i noticed so far is that --version will still show 3.1.5

thanks

**Comment by fiorix** [comment]
During the release I make a mistake and published this binary package with the wrong version, but corrected like 5 minutes later. You must be one of the people that downloaded the wrong one. My bad. :)

**Comment by zechnkaas** [comment]
i am a Windows User and compile myself. Still see the 3.1.5 tag in main.go

**Comment by fiorix** [comment]
master: https://github.com/fiorix/freegeoip/blob/master/apiserver/main.go#L24

v3.2 tag: https://github.com/fiorix/freegeoip/blob/v3.2/apiserver/main.go#L24
