### ISSUE TITLE
Punycode CORS header not working in IE/Edge

### ISSUE THREAD

**Issue by dgsunesen** [fiorix/freegeoip#211]
In IE and Edge the following punycode CORS headers does not work:

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://xn--kodag-uua.dk

```

I think this could be solved if you set `Access-Control-Allow-Origin: *` in stead of the domain requesting it.

**Comment by fiorix** [comment]
I don't see why not use the value passed by the browser via the `Origin` header to render the correct response. Today we use [this library](https://github.com/rs/cors) for handling CORS in the freegeoip web server, so it's unlikely that I will make that change.

CORS headers are only added when necessary today e.g.:

```
$ curl -i -H 'Origin: http://boo' freegeoip.net/json/github.com
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://boo
Content-Type: application/json
Vary: Origin
X-Database-Date: Thu, 09 Feb 2017 01:29:14 GMT
X-Ratelimit-Limit: 15000
X-Ratelimit-Remaining: 14999
X-Ratelimit-Reset: 3600
Date: Wed, 01 Mar 2017 21:35:24 GMT
Content-Length: 255

...
```

If the `Origin` header is omitted, then the server replies with `Vary: Origin` instead.
