### ISSUE TITLE
Provide ipv4/ipv6 only API

### ISSUE THREAD

**Issue by klausenbusk** [fiorix/freegeoip#212]
Hello

Do you plan providing a ipv4/ipv6 only subdomain?
For my use-case, I only care about the ipv4 address, but some of our clients use ipv6.
A ipv4 only subdomain could be useful for that use-case, although I'm not sure if you can do that, now that you use Cloudflare.

Regards Kristian

**Comment by fiorix** [comment]
No plans to do this, sorry. You can do yourself if you run the software on your server and manage DNS the way you want.

Cheers
