### ISSUE TITLE
Lets Encrypt staging server

### ISSUE THREAD

**Issue by mbrevda** [fiorix/freegeoip#218]
While trying to debug why cors headers weren't being returned I restarted the server multiple times. Eventually, I hit the Lets Encrypt rate limit. How can I specify the staging server so that I can continue trying to get cors server setup?

**Comment by fiorix** [comment]
Dunno, but we use the [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) package. Maybe there's something in there.

**Comment by fiorix** [comment]
Let me know if you find something and I'd be happy to review any patches to enable staging servers.
