### ISSUE TITLE
Disable formats

### ISSUE THREAD

**Issue by mbrevda** [fiorix/freegeoip#219]
Is it possible to disable response formats such as jsonp? While this is arguably a form of security by obscurity, nonetheless it can prevent non cors enabled sites from hitting the api.

**Comment by fiorix** [comment]
I don't really see the point in making it optional since you could use a reverse proxy in front of it with the rules you want, for example. If more people need it I wouldn't mind reviewing PRs. It's the first time I hear of this.

**Comment by glerinsonum** [comment]
@fiorix Hello brother. 

Do you have any program, for to extract or to printing all foots or data of application, exe,jpg,any files

example 

Video format: MP4 
Was created: United States, Longitude: 232323 Latitude: 232323.
Type of application: App
etc etc

**Comment by fiorix** [comment]
@glerinsonum no.

**Comment by fiorix** [comment]
@mbrevda we can reopen this discussion if/when there's a patch to support it. Closing for now since I don't have plans to implement it.
