### ISSUE TITLE
dockerimage: server runs as root?!

### ISSUE THREAD

**Issue by jpstotz** [fiorix/freegeoip#220]
I just tested the freegeoip docker image and noticed that the `freegeoip` process is executed using the root user (or did I miss something). Hence the server is running with full root privileges. 
An successful attack on the freegeoip service  would compromise the docker image as well as the complete host system.

From my point of view freegeoip is a webserver providing public services - running it with root permissions is careless.

**Comment by omercnet** [comment]
The container, yes. The host, not at all. 
Since the container only runs the freegeoip having root privileges inside the container doesn't add much more than if you had an unprivileged user, since you could still manipulate the app itself.

**Comment by jpstotz** [comment]
According to the [following guide](http://www.projectatomic.io/docs/docker-image-author-guidance/) using root is not recommended:

> For now, requiring root is dangerous for others and may not be available in all environments. Your image should use the USER instruction to specify a non-root user for containers to run as.

**Comment by omercnet** [comment]
@jpstotz the article states `By default docker containers run as root. A docker container running as root has full control of the host system` which is simply not true.

Unless you run the docker container in privileged mode and/or share the entire host filesystem as a mounted volume, you cannot escape the container

Please read this https://medium.com/@omercnet/dockerized-pwnage-f4cacecfb129 and https://docs.docker.com/engine/security/security/ to learn more about protecting the docker daemon that allows controlling the host

Running as definitely adds security, but if you're not adding unnecessary privileges to the container, there's nothing much you can do with root inside a container. Still, I'll add a non-privileged user.

**Comment by omercnet** [comment]
@jpstotz the article states `By default docker containers run as root. A docker container running as root has full control of the host system` which is simply not true.

Unless you run the docker container in privileged mode and/or share the entire host filesystem as a mounted volume, you cannot escape the container

Please read this https://medium.com/@omercnet/dockerized-pwnage-f4cacecfb129 and https://docs.docker.com/engine/security/security/ to learn more about protecting the docker daemon that allows controlling the host

Running as definitely adds security, but if you're not adding unnecessary privileges to the container, there's nothing much you can do with root inside a container.

**Comment by fiorix** [comment]
We don't use docker in our service but there's people that do. Although I agree with @omercnet that it's not that risky I'm not opposed to having an unprivileged user inside the container. Patches are welcome.

**Comment by bugdanov** [comment]
Patching costs nothing
```
diff --git a/Dockerfile b/Dockerfile
index 90d3c9f..81dfd95 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,8 +3,10 @@ FROM golang:1.7
 COPY cmd/freegeoip/public /var/www
 
 ADD . /go/src/github.com/fiorix/freegeoip
-RUN cd /go/src/github.com/fiorix/freegeoip/cmd/freegeoip && go get && go install
+RUN useradd -ms /bin/bash golang \
+ && cd /go/src/github.com/fiorix/freegeoip/cmd/freegeoip && go get && go install
 
+USER golang
 ENTRYPOINT ["/go/bin/freegeoip"]
 
 EXPOSE 8080
```

**Comment by wbyoung** [comment]
Many if not most docker services run as root. Cintainerization provides separation from the host. This issue should just be closed. The original request and linked articles are missing key points of Docker.

**Comment by jpstotz** [comment]
> Many if not most docker services run as root.

What most people do is one thing. The way that is secure and recommended unfortunately is often a different one.

Regarding root/non-root I found the following sentence in the docker documentation:

> Docker containers are, by default, quite secure; especially if you take care of running your processes inside the containers as non-privileged users (i.e., non-root).
https://docs.docker.com/engine/security/security/#conclusions

From my understanding this sentence implies that for a secure set-up it is recommended to run processes inside a container as non-root.

**Comment by fiorix** [comment]
Alright, b65b9bfc fixes this. It creates user freegeoip to run the service, and sets the capabilities on the binary in case people want to listen on low ports with the unprivileged user.
