### ISSUE TITLE
slow speed when curl by 

### ISSUE THREAD

**Issue by wangtubs** [fiorix/freegeoip#221]
when I use your query by Chrome, it is quite fast to get results. however, I use VPN and use a python script to query, it is very slow. I think it is the problem of Cloudflare you use.
my script is simple like this:
import requests
```
headers = {
    'Accept-Encoding': 'gzip, deflate, sdch',
    'Accept-Language': 'en-US,en;q=0.8',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
}

r = requests.get('http://freegeoip.net/json/108.62.153.229', headers=headers)
print r.content
```
when use VPN, the query is very slow, often over 10s, sometimes over 30s. can you check your cloudflare setting to unblock the query from VPN?

**Comment by fiorix** [comment]
This is more likely to be a problem on the client side. Don't think there's anything specific to this in CloudFlare, at least I haven't configured it for sure.
