### ISSUE TITLE
Localised names

### ISSUE THREAD

**Issue by WildAlex** [fiorix/freegeoip#222]
Can I get localized names of countries, regions and cities?
How it is implemented on http://ip-api.com (doc: http://ip-api.com/docs/api:returned_values) (example: http://ip-api.com/xml/8.8.8.8?lang=ru)

**Comment by fiorix** [comment]
Yes, you can set the Accept-Language header.

```
curl -H 'Accept-Language: ru' freegeoip.net/json/
```
