### ISSUE TITLE
Accessing Freegeoip API through Informatica

### ISSUE THREAD

**Issue by aakashbansal001** [fiorix/freegeoip#223]
Hi Alex,
I am trying to call freegeoip  API through Informatica powercenter  through HTTP transformation and it create url as mention below to call API as:
http://www.freegeoip.net/csv/?IP_or_hostname=$IP_or_hostname

Since your API require call in format freegeoip.net/csv/8.8.8.8 , hence it did not get any IP or hostname ,it return the geocode of the system ip.

Please suggest how to proceed.

**Comment by fiorix** [comment]
If you omit the IP address entirely, it will use the IP address of the caller. This means you can always use the same URL without any transformation, such as: https://freegeoip.net/csv/. Note that the trailing slash is required.

**Comment by aakashbansal001** [comment]
Hi Alex,

My requirement is ,I have list of IPs, and for them I need to call the API to get geocode.
Your solution works when I require geo code for my system IP.
Please suggest.

**Comment by fiorix** [comment]
You can deploy the freegeoip web server locally on your machine and write a script to query it from a list of IPs.
