### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sirmbhe** [fiorix/freegeoip#224]
Hi,

I love your works, and it is exactly what I need for one of my project. And to be honest, I am a noob, so please be kind with me :)

I already download the files from here : https://github.com/fiorix/freegeoip/releases/
And then put it on my webserver. I got this kind of error : 

`Server returned HTTP 404: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> <script type="text/javascript"> //<![CDATA[ var _gaq = _gaq || [];_gaq.push(['_setAccount', 'UA-58562714-1']);_gaq.push(['_trackPageview']);(function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();(function(b){(function(a){"__CF"in b&&"DJS"in b.__CF?b.__CF.DJS.push(a):"addEventListener"in b?b.addEventListener("load",a,!1):b.attachEvent("onload",a)})(function(){"FB"in b&&"Event"in FB&&"subscribe"in FB.Event&&(FB.Event.subscribe("edge.create",function(a){_gaq.push(["_trackSocial","facebook","like",a])}),FB.Event.subscribe("edge.remove",function(a){_gaq.push(["_trackSocial","facebook","unlike",a])}),FB.Event.subscribe("message.send",function(a){_gaq.push(["_trackSocial","facebook","send",a])}));"twttr"in b&&"events"in twttr&&"bind"in twttr.events&&twttr.events.bind("tweet",function(a){if(a){var b;if(a.target&&a.target.nodeName=="IFRAME")a:{if(a=a.target.src){a=a.split("#")[0].match(/[^?=&]+=([^&]*)?/g);b=0;for(var c;c=a[b];++b)if(c.indexOf("url")===0){b=unescape(c.split("=")[1]);break a}}b=void 0}_gaq.push(["_trackSocial","twitter","tweet",b])}})})})(window);//]]> </script><script type="text/javascript"> //<![CDATA[ try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:1498201224,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"c5bfd200525630985613feadad4b0710",petok:"069f3012b9a82bf95624d2706f40ae5158abc9ee-1498208541-1800",zone:"getcomics.info",rocket:"0",apps:{"ga_key":{"ua":"UA-58562714-1","ga_bs":"2"}}}];!function(a,b){a=document.createElement("script"),b=document.getElementsByTagName("script")[0],a.async=!0,a.src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=85b614c0f6/cloudflare.min.js",b.parentNode.insertBefore(a,b)}()}}catch(e){}; //]]> </script> </head><body> <h1>Not Found</h1> <p>The requested URL /json/ was not found on this server.</p> </body></html>`

Am I doing it wrong? Please help me.
I am placing it behind ssl from LetEncrypt and also Cloudflare.

Also, I tried to read the information on the github page. I don't think placing the files on webserver isn't the only step that I should do, am I? And I tried to do the docker thing, and it just added my confusion. I am sorry, I still have a lot to learn.

Thanks

**Comment by fiorix** [comment]
Hard to tell what the actual problem could be by looking at this html/js error from CloudFlare. Does it work when you try the IP of your server directly?

The simplest way to test is by running `curl` to your server.

**Comment by fiorix** [comment]
lmk if you still need help and i can reopen this
