### ISSUE TITLE
List of values for country & region

### ISSUE THREAD

**Issue by awcutting** [fiorix/freegeoip#229]
I’m setting up an integration with a 3rd party tool that uses freegeoip.net, and I need to ensure that any values returned are mapped to the picklist values in our CRM.

I can see it's referencing ISO codes, but want to confirm the exact values (same for for state/region as well). If there's any easy way for me to reference an exact list of possible values for country and region it would be much appreciated!

Thanks

**Comment by fiorix** [comment]
Hey, this is a bit out of scope here. You're better off looking at the MaxMind GeoLite2 page / docs for such list. Sorry but there's no much I can do to help.

**Comment by awcutting** [comment]
No worries - figured I'd reach out and see. Thanks for the reply!
