### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by Ardinis** [fiorix/freegeoip#230]
Hello,

I tried to run the docker image on the local interface but i have this behavior:

Command used:
`docker run --restart=always -p 421:421 -d fiorix/freegeoip -http 127.0.0.1:421`

Result:
`curl 127.0.0.1:421`
`curl: (52) Empty reply from server`

Everything is ok when binded on 0.0.0.0.

**Comment by fiorix** [comment]
seems like a problem with docker binding not freegeoip... maybe -p allows to configure ip:port, not sure
