### ISSUE TITLE
ipv6 based locations less likely?

### ISSUE THREAD

**Issue by MACscr** [fiorix/freegeoip#233]
Sorry for bringing this back up, but aren't you finding ipv6 addresses to be less likely to contain the proper or any for that matter, location information? I am finding that of the responses I am getting that have no location, 90% are ipv6.

**Comment by fiorix** [comment]
Yeah there's no much we can do about this actually. The quality of the database for v6 addresses is definitely not as good as v4.

**Comment by MACscr** [comment]
Then it would be really nice if we could force ipv4 only from your API. I know self hosting is an option, but I don't think this should be required.

**Comment by fiorix** [comment]
The only way you can force ipv4 is if you access the API via ipv4 instead.
