### ISSUE TITLE
Successfully response with empty location

### ISSUE THREAD

**Issue by JIucToyxuu** [fiorix/freegeoip#235]
For some IP addresses returns success response but without country_code. Provide one example below:

Request: https://freegeoip.net/json/82.145.211.193
Response: {"ip":"82.145.211.193","country_code":"","country_name":"","region_code":"","region_name":"","city":"","zip_code":"","time_zone":"Europe/Vaduz","latitude":47,"longitude":8,"metro_code":0}

**Comment by fiorix** [comment]
This is normal. Service returns what's in the database.

**Comment by eliaspizarro** [comment]
What about with IP that doesnt exist in your DB?

https://freegeoip.net/json/200.75.7.65

**Comment by fiorix** [comment]
The IP entry does exist, but doesn't have city information.
