### ISSUE TITLE
somtimes ip show mac address 

### ISSUE THREAD

**Issue by xiaoz0** [fiorix/freegeoip#238]
sometimes ip show mac address 240e:e8:f044:dfae:1:1:7cbb:abfc

**Comment by fiorix** [comment]
Not sure what the question is. The freegeoip API only performs lookup on IP addresses, which are either the source IP address (if omitted) or an IP provided by the user in the API call, e.g. /json/{ip}.

**Comment by omercnet** [comment]
@xiaoz0 this looks like an IPv6 address and not a mac address
