### ISSUE TITLE
404 when deployed under context path

### ISSUE THREAD

**Issue by jaecktec** [fiorix/freegeoip#239]
We are deploying the Docker Image and have to map it to a context path (domain.com/geoip) but then we get a 404. Is there a way to get this working properly?

**Comment by fiorix** [comment]
You have to inform the freegeoip web server that you have an prefix path in your API.

That is the very first option described on the help :)

```
$ ./freegeoip -h
Usage of ./freegeoip:
  -api-prefix string
    	URL prefix for API endpoints (default "/")
```

Closing this but happy to reopen if you have any more troubles.

**Comment by jaecktec** [comment]
Ok haven't installed the api locally. Thanks

**Comment by fiorix** [comment]
This works too: `docker run fiorix/freegeoip --help`
