### ISSUE TITLE
Docker constantly restarting when declaring HTTPS

### ISSUE THREAD

**Issue by chrispage1** [fiorix/freegeoip#241]
Hi,

When I declare https flag with `-https :8443` (so run HTTPS on port 8443) it just kicks off the container into an infinite restart loop. Any ideas? Same happens if I try and customise the HTTP port!

Thanks,
Chris.

**Comment by chrispage1** [comment]
Managed to resolve this after some time playing with various configurations. Just for reference this works for me - 

`docker run --restart=always -p 80:8080 -p 443:8443 -d fiorix/freegeoip -https :8443 -http :8080 -letsencrypt -letsencrypt-hosts your-host.com`

**Comment by fiorix** [comment]
👍
