### ISSUE TITLE
localisation doesn't work for all Accept-language header types

### ISSUE THREAD

**Issue by emilburzo** [fiorix/freegeoip#248]
Hey, great project!

I've noticed that not every [Accept-language header type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) works, e.g.:

Works:
```
$ curl -s -H 'Accept-Language: de' freegeoip.net/json/79.119.123.222 | jq .country_name
"Rumänien"
```

Doesn't work:
```
$ curl -s -H 'Accept-Language: de-DE' freegeoip.net/json/79.119.123.222 | jq .country_name
"Romania"
```

**Comment by fiorix** [comment]
That's because we don't parse Accept-Language properly. Instead, we use the value of Accept-Language directly in the response map, and if there's no match, fallback to english:

https://github.com/fiorix/freegeoip/blob/master/apiserver/api.go#L230

Patches are welcome :)

**Comment by emilburzo** [comment]
Got it :)

If I were to give it a go, should the parser output just be the language code?

E.g.:

`fr-CH` -> `fr`
`fr` -> `fr`
`en;q=0.8` -> `en`

**Comment by fiorix** [comment]
Exactly. Ideally you'd parse multiple languages and use the first available (in case of multiple q=X), and always fallback to english.
