### ISSUE TITLE
FF 56.0 No Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by pavelkarinin** [fiorix/freegeoip#250]
JavaScript:

```
var xhr = new XMLHttpRequest();
xhr.open('GET', 'http://freegeoip.net/json/', true);
xhr.onloadend = function() { ... };
xhr.send();
```

Request headers:

```
Host: freegeoip.net
User-Agent: Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/56.0
Accept: text/html,application/xhtml+xm…plication/xml;q=0.9,*/*;q=0.8
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET	
Origin: http://192.168.0.2:1000
Connection: keep-alive
```

Firefox:

`There is no CORS header "Access-Control-Allow-Origin"`

**Comment by fiorix** [comment]
This came up before in #170 and other people confirmed that it works. I don't have FF and have no plans to do any more thorough investigation - no time, limited internet access atm, etc.

You could download the freegeoip web server and test locally. We use https://github.com/rs/cors for handling cors, and if what you describe is a bug, it is in that package instead.
