### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by usman-86** [fiorix/freegeoip#251]
> Severity: Warning
> Message: file_get_contents(http://freegeoip.net/json/39.37.152.1): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

I am getting this error since 24 hours ... i am wondering how long this will display on my site 
is there any solution for this please help ...

**Comment by fiorix** [comment]
Hmm. This is odd. The one thing I've seen in the past is people using common hosting companies that had multiple services using something in php that used freegeoip, and their services having the same egress IP would influence each other's quota.

However, I've also seen stale entries in redis, but those were fixed long ago and hasn't happened in at least 2 or more years.

Before we go too deep into this, can confirm whether you're still having this issue? Please provide your source IP so we can check in our quota system and also the X-Ratelimit-* headers. cc @packetrich

**Comment by fiorix** [comment]
Crickets here, closing.
