### ISSUE TITLE
Alternative sources?

### ISSUE THREAD

**Issue by stereobooster** [fiorix/freegeoip#252]
Did you consider to use alternative sources? Like:

- http://lite.ip2location.com/database/ip-country-region-city-latitude-longitude-zipcode-timezone
- https://db-ip.com/db/download/city
- https://location.services.mozilla.com/downloads

PS project is amazing: go, letsencrypt, prometeus. Well done 👍

**Comment by fiorix** [comment]
Hey we had different databases along the way... There's some of this documented in the [history](https://github.com/fiorix/freegeoip/blob/master/HISTORY.md) of freegeoip.

In the distant past I was contacted by various providers, including ip2location, and considered using them, but for simplicity I opted to use maxmind for the accuracy of their free data.

If you think this is trivial and would like to give it a shot, I'm happy to review code and would consider merging, but I'm not doing it myself.

**Comment by Yamakasi** [comment]
I think it would be great to merge them but do they match format ?

Or is there a chance to just load another DB instead of the mindmax free one ? as that one is far from accurate.

**Comment by fiorix** [comment]
Yeah last I checked the db from ip2location didn't match. With the current code: no, you cannot load another db.

If you have plans to give it a shot please let me know and I'll reopen this.
