### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by mpaolo** [fiorix/freegeoip#253]
Hi

connection to https://freegeoip.net/json/ fails with this error with some (Chromium-based) browsers, like
Opera 36.0.2130.80
SRWare Iron  49.0.2600.0
(on Windows XP 32-bit)
details are:
"The client and server don't support a common SSL protocol version or cipher suite. This is likely to be caused when the server needs RC4, which is no longer considered secure."

thx

**Comment by fiorix** [comment]
This is not really possible on our end, and we don't offer nor require rc4.
