### ISSUE TITLE
Why isn't json returning city, region or country

### ISSUE THREAD

**Issue by ConfusedRunningGuy** [fiorix/freegeoip#254]
Why isn't the api returning city,region or country in the returned json?

**Comment by fiorix** [comment]
Good question. What's the HTTP return status? If it is 200 (Status OK) it means the IP you're looking for is not in the IP database. For other return status the response body should contain an explanation.

**Comment by ConfusedRunningGuy** [comment]
Ahh my connection is dynamic not static and provider changed switch to a
new facility that may not be recorded.  Either way I found a solution using
GeoIp to produce the lat/lng coordinates and another api to produce the
city if GeoIP doesn't include the city.
