### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by Lvm-Daud** [fiorix/freegeoip#255]
I was trying to 93.127.232.122 IP but it shows location US, instead of Germany.

**Comment by MACscr** [comment]
Thats an issue with maxmind that provides the database, not freegeoip. You can go to a site like https://www.iplocation.net/, enter that same ip and you will see that maxmind does indeed have a US entry for it even though the others have the right one.

**Comment by fiorix** [comment]
Right. There's no much we can do here.
