### ISSUE TITLE
403 responses because of shared IP

### ISSUE THREAD

**Issue by bert-w** [fiorix/freegeoip#256]
I have the feeling that my server is being denied access to the freegeoip API, because multiple servers are using the same IP to query freegeoip. Is there any solution to circumvent this, without switching to a dedicated IP? Like an API key?

API key feature hereby suggested.

**Comment by fiorix** [comment]
Hey there's no much I can do right now to mitigate this. No plans to implement API key either.

The only thing I can suggest is that you deploy your own instance of freegeoip somewhere (own vps, or heroku) and make your clients use that one instead.
