### ISSUE TITLE
free service at freegeoip.net - all responses?

### ISSUE THREAD

**Issue by morrow95** [fiorix/freegeoip#257]
As far as the free service at freegeoip.net goes... what are the possible responses that can be sent back?  You only mention a 403 forbidden header when the 15k limit per hour is reached.

So other than a 403 and 200 obviously, what are the other responses generated and their conditions?  For example... an IP not found, invalid data sent, and so on.  Without knowing how responses are handled on your end for this that makes it kind of tough to perform any logic/conditionals/error handling on my end when using this.

**Comment by fiorix** [comment]
There's only 3 possible statuses:

* HTTP 200 OK
* HTTP 403 Forbidden
* HTTP 503 Service Unavailable (this may happen if the database failed to load)
