### ISSUE TITLE
AWS ALB path forwarding to 8080/json/

### ISSUE THREAD

**Issue by segersniels** [fiorix/freegeoip#258]
Would it be possible to access the `/json/` path directly from port `8080` so I can point my api traffic coming from `https://foo.com/v1/geo` directly to `<container>:8080` to get the `/json/` return?

As I currently have a load balancer set up on Amazon Web Services that points to the container at port `8080` which doesn't return anything.

**Comment by fiorix** [comment]
There's no option to remove the `/json/` prefix in freegeoip. You should do that in a reverse proxy sitting in front of the freegeoip web server.
