### ISSUE TITLE
Not working when AdBlock Running

### ISSUE THREAD

**Issue by shabbir-dhangot** [fiorix/freegeoip#261]
I am not able to hit freegeoip when AdBlock is running.

This is breaking my system. My target audience may have adblock. At their end some of my website functionality will not work. Attached screenshot

What should I do?

![image](https://user-images.githubusercontent.com/8267282/34253501-e6257a50-e66d-11e7-986a-034778666ab4.png)

**Comment by MACscr** [comment]
Self host it like anyone else that relies on its functionality. We should not be basking fiorix to pay for hosting for our own needs.

**Comment by shabbir-dhangot** [comment]
Self host is good solution.

**Comment by fiorix** [comment]
Correct. There's no much I can do other than offer the freegeoip web server for others to host on their own vps/domain. Closing.
