### ISSUE TITLE
IP Address: 212.121.135.169 is wrong, it goes to Japan! Should be Stuttgart, Germany.

### ISSUE THREAD

**Issue by cindyorbcomm** [fiorix/freegeoip#262]
Hi,

When I tested http://freegeoip.net/?q=212.121.135.169, no country was displayed.

Could you look it in your database?

Thanks,
Cindy

**Comment by Rockstar04** [comment]
All IP data is from the free version of the MaxMind database. Any issues need to be addressed with MaxMind. http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by cindyorbcomm** [comment]
ok. thanks.
