### ISSUE TITLE
Encountered `OpenSSL::SSL::SSLError: hostname "freegeoip.io" does not match the server certificate`

### ISSUE THREAD

**Issue by dseeto** [fiorix/freegeoip#264]
From other closed issues, it seems like cert management is automated with https://godoc.org/golang.org/x/crypto/acme/autocert#Manager and is supposed to renew 30 days before expiration.  However, I encountered `OpenSSL::SSL::SSLError: hostname "freegeoip.io" does not match the server certificate` from `2018-02-10 12:08 pm` to `2018-02-11 09:11 am` PST. Was wondering if there was a known issue with the cert during that period.

**Comment by Foggyx420** [comment]
if the certificate did update, wouldn't a restart of the service be required? much like if your certificate updates for a webserver a restart of the daemon is required

**Comment by dseeto** [comment]
@fiorix, not sure how the cert renewal is setup exactly, but are the app servers or the daemon restarted after a renewal to pick up the new cert?

**Comment by fiorix** [comment]
You have to restart the server to update the certificate. We use https://godoc.org/golang.org/x/crypto/acme/autocert to manage this.

**Comment by batshoes** [comment]
I'm getting a lot of these errors on my site as well. I'm not sure If it's something on your end or mine. What can I show you to help ?

**Comment by adrianorob** [comment]
I'm having the same problem right now. And the strange thing is that is only in the principal page that it shows this error, other pages that uses it does not happen the error.

**Comment by hugoh1995** [comment]
Having same issue at the moment!

**Comment by culov** [comment]
Same issue here

**Comment by adrianorob** [comment]
I changed my service to google ip location

**Comment by batshoes** [comment]
Freegeoip moved servers from freegeoip.io to freegeoip.net...
Updating the gem to `~> 1.4.5` fixed this for me.

**Comment by alexrolls** [comment]
To fix problem without changing gem version,
In config/initializers/geocoder.rb
extend Geocoder.configure
with option:
```
freegeoip: { host: 'freegeoip.net' }
```
