### ISSUE TITLE
Use Alpine Linux Base Docker Image

### ISSUE THREAD

**Issue by westy92** [fiorix/freegeoip#265]
Currently the Dockerfile is using a base image of `golang:1.9` (274 MB).
This could be switched to an Alpine Linux version `golang:1.9-alpine` (83 MB) to drastically reduce the image size.

https://hub.docker.com/r/library/golang/tags/

**Comment by fiorix** [comment]
See #268

**Comment by justgage** [comment]
Made a PR on the new repo: https://github.com/apilayer/freegeoip/pull/1
