### ISSUE TITLE
Data Format Documentation

### ISSUE THREAD

**Issue by westy92** [fiorix/freegeoip#266]
Here's some example data:
```json
{  
   "ip":"1.2.3.4",
   "country_code":"US",
   "country_name":"United States",
   "region_code":"WA",
   "region_name":"Washington",
   "city":"Mukilteo",
   "zip_code":"98275",
   "time_zone":"America/Los_Angeles",
   "latitude":47.913,
   "longitude":-122.3042,
   "metro_code":819
}
```

However, I cannot find documentation detailing what format the data is in.
For instance, is the country_code ISO 3166-1 alpha-2? Is the time_zone from the IANA TZ database? Etc.

**Comment by fiorix** [comment]
There's some documentation about this on maxmind's site, oddly enough I found it only in the documentation of the "csv" database. Same data though.

https://dev.maxmind.com/geoip/geoip2/geoip2-city-country-csv-databases/

country_code is http://en.wikipedia.org/wiki/ISO_3166-1
time_zone is http://www.iana.org/time-zones
