### ISSUE TITLE
Troubleshooting Let's Encrypt Certificate Failures 

### ISSUE THREAD

**Issue by own3mall** [fiorix/freegeoip#269]
How do we figure out why Let's Encrypt is failing?

Is the reason why Let's Encrypt integration failed logged anywhere?  I can't seem to figure out why my certificate won't pull / renew anymore.

I run this command:

```
docker run --restart=always -p 33333:33333 -p 443:443 -v /var/www/geoservices:/tmp/www -i -t fiorix/freegeoip -http :33333 -https :443 -public /tmp/www -letsencrypt -letsencrypt-email myemail@myemail.com -letsencrypt-hosts www.{MYDOMAIN},{MYDOMAIN}
```

and get this output when using https://

```
[error] 2018/03/01 17:31:33 http: TLS handshake error from {MYIP}: acme/autocert: missing certificate
[error] 2018/03/01 17:31:34 http: TLS handshake error from {MYIP}: acme/autocert: missing certificate
```

I had it working at one point, but now it appears to be failing, and I don't know how to troubleshoot the error code received from Let's Encrypt.  Can anyone help?

**Comment by own3mall** [comment]
It looks like the acme autocert package needs to be updated.

https://community.letsencrypt.org/t/crypto-golang-org-x-crypto-acme-autocert-how-to-troubleshoot-lets-encrypt-errors-with-docker-packages/54555

**Comment by OlagStegan** [comment]
Thanks own3cloud, I've been fighting this one for the last 3 days without any progress or insight to the error. 
The resolution appears to be simple - a rebuild with the updated "golang.org/x/crypto/acme/autocert"
As that seems like a priority, is their any news on when this will be upgraded?
or
as I have a valid cert outside docker how we could implement the external cert?

**Comment by fiorix** [comment]
Hey please see #268. Closing this.
