### ISSUE TITLE
Change limit not working in Heroku app?

### ISSUE THREAD

**Issue by IshwarBhat** [fiorix/freegeoip#272]
I was not sure where to ask for help with this, hence raising an issue here. Any help is appreciated.
I tried running `freegeoip` as a Heroku app by first cloning the app source code in my local Windows machine. I need to increase the limit of 10,000 requests per hour. To do this, I tried two methods:
1. Change the contents of `apiserver/config.go` by adding a line `RateLimitLimit:      0,` inside `func NewConfig() *Config { return &Config{ } }`
2. Create a file `prod.env` with the line `FREEGEOIP_RATELIMITLIMIT=50000`
Neither of which worked. When I open my app home page, I still see  

> 9997 calls remaining, resets in 59 minutes

Where am I going wrong?

**Comment by fiorix** [comment]
Closing this due to #268.

**Comment by IshwarBhat** [comment]
Oops my bad.
