### ISSUE TITLE
Maxmind GeoLite2 free database will 

### ISSUE THREAD

**Issue by tachtler** [fiorix/freegeoip#274]
Hi,

what about the announcement of MaxMind about the free GeoLite2 database change to 2019, January?

>  In addition, in 2019, latitude and longitude coordinates in the GeoLite2 databases will be removed.*
>
> \* GeoLite2 databases are free IP geolocation databases comparable to, but less accurate than,
> MaxMind’s GeoIP2 databases. Latitude and longitude coordinates will continue to be provided in
> GeoIP2 databases. Please check back for updates. 

Thank you!
Klaus.

**Comment by fiorix** [comment]
Please see #268
