### ISSUE TITLE
Enable CORS on server

### ISSUE THREAD

**Issue by victorgcramos** [fiorix/freegeoip#275]
I'm trying to do a request from axios and i get this error:
`Failed to load https://api.ipstack.com/check?access_key=****: Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

Take a look at this: https://stackoverflow.com/a/41606624

**Comment by fiorix** [comment]
Please see #268

**Comment by victorgcramos** [comment]
thanks!
