### ISSUE TITLE
ipstack return server IP

### ISSUE THREAD

**Issue by Wooody82** [fiorix/freegeoip#278]
Hi,
I am trying to get the user ip by using PHP function to return the IP, But its return the website Server IP..  What is the problem?

    $ch = curl_init('http://api.ipstack.com/check?access_key=API-KEY');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $json = curl_exec($ch);
    curl_close($ch);
    $api_result = json_decode($json, true);
     return $api_result['ip'];

Thanks

**Comment by fiorix** [comment]
See #268
