### ISSUE TITLE
Wrong location against ip addresses

### ISSUE THREAD

**Issue by aliabbas-2012** [fiorix/freegeoip#284]
Dear team its a swear issue in your logic , it always tell us wrong location against our ip, it takes us to Sindh , but we are living in punjab pakistan. Our data getting wrong , please solve your issue asap

**Comment by vagari** [comment]
Two things. This is not an active project, so there won't be an update. Two, the project (and its successors) pulls its database from a third party. You're likely seeing a site that has an old version of this project running, with an outdated database.

**Comment by CarlosJa** [comment]
The project was bought by a company that's not really keeping up with the project. If you're looking for a reliable GeoIP Provider you can look into www.snoopi.io  they also provide JSONP SSL with the free version of the api

**Comment by laurentpellegrino** [comment]
You should have a look at https://ipregistry.co.

**Comment by fiorix** [comment]
The original service hasn't been running for years. See #268 for details.
