### ISSUE TITLE
SSL issue on production on 3.210.48.126

### ISSUE THREAD

**Issue by dimalusa** [fiorix/freegeoip#288]
Hello, 

Since today around 12h30, we can find an SSL issue on production node 3.210.48.126.
Can you fix it ???
(It's ipstack project.)

Thanks

**Comment by rcknr** [comment]
@dimalusa This service is retired a long time ago. Maybe I can help you with an alternative?

**Comment by zecafeitosa** [comment]
Here the same :/

**Comment by dimalusa** [comment]
Some news please ??

**Comment by rcknr** [comment]
@dimalusa Told you there won't be a quick fix. The company that owns this doesn't maintain the service anymore. If you need more info reach me out on Twitter under the same nickname.

**Comment by dimalusa** [comment]
It seems to be OK now.
Is it better to use https://ipapi.com/ than https://ipstack.com/ ?
Thank you.

**Comment by fiorix** [comment]
The original service hasn't been running for years. See #268 for details.
