### ISSUE TITLE
link https://status.ipstack.com/ get 404

### ISSUE THREAD

**Issue by David-Charlesia** [fiorix/freegeoip#289]
this link on home page get 404
![image](https://user-images.githubusercontent.com/50445620/115379186-941b8380-a1d1-11eb-9226-cef1e4dffff9.png)

https://status.ipstack.com/
![image](https://user-images.githubusercontent.com/50445620/115379074-7a7a3c00-a1d1-11eb-82bd-2ae35a215bf9.png)

**Comment by fiorix** [comment]
Please see #268.
