### ISSUE TITLE
cURL error 52: Empty reply from server 

### ISSUE THREAD

**Issue by htuzel** [fiorix/freegeoip#290]
for 2 days, it is not working stabil. It is not good for a paid service!

**Comment by badoux** [comment]
Same, the service is down since yesterday ...

**Comment by MostafaElAyoubi** [comment]
indeed service is down with no communication. It would be great to get some information on what is happening.

**Comment by badoux** [comment]
@MostafaElAyoubi  https://twitter.com/apilayer/status/1410104024599171076 They are working on the issue

**Comment by fiorix** [comment]
Please see #268.
