### ISSUE TITLE
freegeoip.net appears to be down

### ISSUE THREAD

**Issue by chrisgward** [fiorix/freegeoip#36]
$ curl freegeoip.net
curl: (7) Failed connect to freegeoip.net:80; Connection timed out

**Comment by parweensingh** [comment]
freegeoip.net is most of the time down in the last 2-3 days. We are using http in our app, still it doesn't work. We have been using the service for the past 6 months. Such huge percentage of downtime was never observed. Kindly look into the issue. Thanks for the service though.

**Comment by fiorix** [comment]
Have you seen #165?

**Comment by profeg** [comment]
try to use its mirror freegeoip.io
```
:freegeoip => {
    :host => "freegeoip.io"
  }
```

**Comment by chrisgward** [comment]
If we could stop necrothreading this ticket, that'd be great
