### ISSUE TITLE
change broke things

### ISSUE THREAD

**Issue by squirrelpiles** [fiorix/freegeoip#78]
Hello,

The change that does the "browser check" breaks code I have deployed to remote systems.

Can this be rolled back for like 1 hour so I can recover?

thx

**Comment by bauhausweb** [comment]
This error still occurs when doing a client based JSON request. Any updates on this one?

**Comment by fiorix** [comment]
This is because the servers are overloaded. There's been a lot more SSL than usual and the 2 servers we have for the public service cannot handle it all.

http://imgur.com/VsowHRD
