### ISSUE TITLE
freegeoip.net - 503 from HTTP client

### ISSUE THREAD

**Issue by khomich** [fiorix/freegeoip#79]
Service returns 503 if I use my http client, but still good when run ip lookup in browser.

**Comment by bauhausweb** [comment]
This error still exists. Any updates on Cloudflare blocking JSON from a http client request..?

**Comment by jhg-tgu** [comment]
I have 503 only when I use my own DB URL

**Comment by fiorix** [comment]
You should look for logs in the console to identify what error you're getting in the server.

It returns 503 when no db is available.
