### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by steverob** [fiorix/freegeoip#89]
For a total newbie in Go are there clear instructions as to how I can deploy this on my Ubuntu server?

I dont have docker installed in it and I am not planning to go that way either. 

Thanks in advance :heart:

**Comment by hdesouky** [comment]
I tried to host the freegeoip in azure host (it supports Go now). But i can't run the application since it always stops after loading the database, below is the output of stdout:

```
2016/05/05 07:43:01 freegeoip http server starting on :8080
2016/05/05 07:43:01 database loaded: D:\local\Temp\freegeoip\db.gz
```

Any idea how to debug?

**Comment by fiorix** [comment]
Those messages indicate that the server has started and downloaded the IP database, and should be serving requests. I haven't used Azure for anything other than running vms, and since my trial has expired cannot try to reproduce what you're doing.
