### ISSUE TITLE
API and CloudFlare DDoS protection redirection issue

### ISSUE THREAD

**Issue by toin0u** [fiorix/freegeoip#99]
Hi Alexandre,

First of all thanks for your work to this great project!
I'm a maintainer of the [Geocoder PHP](https://github.com/geocoder-php) library. We use freegeoip as a provider :)

It worked very well but since you moved the service behind the CloudFlare DDoS protection. It's not possible anymore to consume the API as this protection uses javascript to redirect to the resource.

``` bash
$ curl http://freegeoip.net/json/74.200.247.59
```

Hope this gives meaning and hope it can be solved :)

**Comment by danielbachhuber** [comment]
I just experienced this same error message when calling `https://freegeoip.net`. I changed my request to use `http` and no longer experienced the CloudFlare error.

**Comment by fiorix** [comment]
That's expected. Only the API endpoints are configured to not do this.

**Comment by danielbachhuber** [comment]
Sorry, to clarify, I was calling an API endpoint. However, the error no longer reproduces.
